import {GREEN, LINE, SURFACE, TEXT, TEXT_MUTED} from '../theme';

export const authStyles = {
  authContent: {
      flexGrow: 1,
      paddingHorizontal: 26,
      paddingVertical: 36,
      justifyContent: 'center',
    },
  authBrandBlock: {
      alignItems: 'center',
      marginBottom: 28,
    },
  authIcon: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 12},
      shadowOpacity: 0.4,
      shadowRadius: 20,
      elevation: 8,
    },
  authBrand: {
      color: TEXT,
      fontSize: 32,
      fontWeight: '900',
      marginBottom: 12,
      letterSpacing: -0.5,
    },
  authTitle: {
      color: TEXT,
      fontSize: 22,
      fontWeight: '800',
      textAlign: 'center',
      letterSpacing: -0.3,
    },
  authSub: {
      color: TEXT_MUTED,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      marginTop: 8,
      textAlign: 'center',
      maxWidth: 260,
    },
  authForm: {
      width: '100%',
      maxWidth: 360,
      alignSelf: 'center',
      gap: 10,
    },
  authField: {
      height: 52,
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
  authInput: {
      flex: 1,
      color: TEXT,
      fontSize: 14,
      fontWeight: '600',
      padding: 0,
    },
  authPrimaryButton: {
      height: 52,
      borderRadius: 26,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 4,
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.38,
      shadowRadius: 16,
      elevation: 6,
    },
  authPrimaryButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '800',
    },
  authDividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginVertical: 4,
    },
  authDividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: LINE,
    },
  authDividerText: {
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '700',
    },
  kakaoButton: {
      height: 52,
      borderRadius: 26,
      backgroundColor: '#FEE500',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 9,
    },
  kakaoIconText: {
      color: '#181600',
      fontSize: 16,
      fontWeight: '800',
    },
  kakaoButtonText: {
      color: '#181600',
      fontSize: 14,
      fontWeight: '700',
    },
  googleButton: {
      height: 52,
      borderRadius: 26,
      backgroundColor: '#F8FAFC',
      borderWidth: 1,
      borderColor: '#E2E8F0',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 9,
    },
  googleIconText: {
      color: '#3B72F0',
      fontSize: 16,
      fontWeight: '800',
    },
  googleButtonText: {
      color: '#111827',
      fontSize: 14,
      fontWeight: '700',
    },
  authSwitchButton: {
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
    },
  authSwitchText: {
      color: '#5ECBFA',
      fontSize: 13,
      fontWeight: '700',
    }
};
