import {Platform} from 'react-native';
import {GREEN, LINE, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const baseStyles = {
  root: {
      flex: 1,
      backgroundColor: SCREEN,
    },
  header: {
      height: 62,
      paddingHorizontal: 22,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: SCREEN,
    },
  brand: {
      fontSize: 24,
      fontWeight: '900',
      color: TEXT,
      letterSpacing: -0.5,
    },
  brandSub: {
      fontSize: 10,
      fontWeight: '600',
      color: TEXT_MUTED,
      marginTop: 1,
      letterSpacing: 0.2,
    },
  headerPill: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  headerPillText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '800',
    },
  mapShell: {
      height: Platform.OS === 'ios' ? 255 : 245,
      marginHorizontal: 16,
      marginBottom: 14,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: SURFACE,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.3,
      shadowRadius: 24,
      elevation: 8,
    },
  navigationMapShell: {
      height: Platform.OS === 'ios' ? 470 : 450,
      marginHorizontal: 0,
      marginBottom: 0,
      borderRadius: 0,
      shadowOpacity: 0,
      elevation: 0,
      zIndex: 0,
    },
  navigationMapFull: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      height: undefined,
    },
  webview: {
      flex: 1,
      backgroundColor: '#e5e7eb',
    },
  mapOverlay: {
      position: 'absolute',
      left: 14,
      right: 14,
      top: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 14,
      backgroundColor: 'rgba(14,25,40,0.88)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.07)',
    },
  mapTitle: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
    },
  mapSub: {
      marginTop: 3,
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '600',
    },
  navigationBanner: {
      position: 'absolute',
      left: 16,
      right: 16,
      top: 16,
      minHeight: 60,
      borderRadius: 16,
      backgroundColor: GREEN,
      paddingHorizontal: 16,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.35,
      shadowRadius: 20,
      elevation: 8,
    },
  navigationBannerIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: 'rgba(255,255,255,0.22)',
      alignItems: 'center',
      justifyContent: 'center',
    },
  navigationBannerTextBox: {
      flex: 1,
    },
  navigationBannerTitle: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '800',
    },
  navigationBannerSub: {
      color: 'rgba(255,255,255,0.78)',
      fontSize: 11,
      fontWeight: '600',
      marginTop: 2,
    },
  loadingOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(14,25,40,0.7)',
      alignItems: 'center',
      justifyContent: 'center',
    },
  loadingCard: {
      minWidth: 140,
      alignItems: 'center',
      gap: 12,
      padding: 22,
      borderRadius: 20,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
    },
  loadingText: {
      color: TEXT,
      fontSize: 13,
      fontWeight: '700',
    },
  contentShell: {
      flex: 1,
      backgroundColor: SCREEN,
    },
  runNavigationStage: {
      flex: 1,
      backgroundColor: SCREEN,
      overflow: 'hidden',
    },
  navigationContentShell: {
      backgroundColor: 'transparent',
      marginTop: 0,
      zIndex: 3,
      elevation: 3,
    }
};
