import {GREEN, LINE, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const communityStyles = {
  communitySearchCard: {
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.14,
      shadowRadius: 14,
      elevation: 4,
    },
  communitySearchBox: {
      height: 46,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
    },
  communitySearchInput: {
      flex: 1,
      color: TEXT,
      fontSize: 14,
      fontWeight: '600',
      padding: 0,
    },
  communityFilterRow: {
      gap: 8,
      paddingTop: 10,
      paddingRight: 4,
    },
  communityFilterChip: {
      height: 34,
      minWidth: 64,
      borderRadius: 17,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
  communityFilterChipActive: {
      backgroundColor: GREEN,
      borderColor: GREEN,
    },
  communityFilterText: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '700',
    },
  communityFilterTextActive: {
      color: '#fff',
    },
  communityRouteCard: {
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 5,
    },
  communityRouteImageBox: {
      height: 152,
      borderRadius: 12,
      backgroundColor: '#111827',
      overflow: 'hidden',
      marginBottom: 12,
    },
  communityImageTopRow: {
      position: 'absolute',
      left: 10,
      right: 10,
      top: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
  communityLocationPill: {
      minHeight: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(14,25,40,0.82)',
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      flexShrink: 1,
    },
  communityLocationPillText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '700',
    },
  communityStartBadge: {
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(14,25,40,0.82)',
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
  communityStartBadgeOk: {
      backgroundColor: 'rgba(16,201,124,0.22)',
    },
  communityStartBadgeText: {
      color: '#A8C6FC',
      fontSize: 10,
      fontWeight: '700',
    },
  communityStartBadgeTextOk: {
      color: '#6EE7B7',
    },
  communityRouteBody: {
      gap: 10,
    },
  communityRouteTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
  communityRouteTitleBox: {
      flex: 1,
    },
  communityRouteTitle: {
      color: TEXT,
      fontSize: 17,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
  communityRouteMeta: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 4,
    },
  communityAuthorBadge: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  communityAuthorInitial: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '800',
    },
  communityAuthorText: {
      color: '#A8C6FC',
      fontSize: 12,
      fontWeight: '600',
    },
  communityDetailBox: {
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
    },
  communityDetailText: {
      color: TEXT,
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '600',
    },
  communityTags: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
      marginTop: 10,
    },
  communityTag: {
      height: 28,
      borderRadius: 14,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
  communityTagText: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
    },
  communityDetailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 16,
    },
  communityBackButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
    },
  communityDetailHeaderText: {
      flex: 1,
    },
  communityDetailKicker: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  communityDetailTitle: {
      color: TEXT,
      fontSize: 22,
      fontWeight: '800',
      marginTop: 3,
      letterSpacing: -0.3,
    },
  communityDetailMapCard: {
      height: 260,
      borderRadius: 16,
      backgroundColor: '#111827',
      borderWidth: 1,
      borderColor: LINE,
      overflow: 'hidden',
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 6,
    },
  communityDetailMapTop: {
      position: 'absolute',
      left: 10,
      right: 10,
      top: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
  communityDetailMapBottom: {
      position: 'absolute',
      left: 14,
      right: 14,
      bottom: 14,
      borderRadius: 14,
      backgroundColor: 'rgba(14,25,40,0.88)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.07)',
      padding: 14,
    },
  communityDetailMapTitle: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '700',
    },
  communityDetailMapSub: {
      color: '#A8C6FC',
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 4,
    },
  communityDetailSummary: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
    },
  communityDetailMetric: {
      flex: 1,
      minHeight: 72,
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
      justifyContent: 'center',
    },
  communityDetailMetricLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      marginBottom: 6,
      letterSpacing: 0.3,
    },
  communityDetailMetricValue: {
      color: TEXT,
      fontSize: 16,
      fontWeight: '800',
    },
  communityDetailSection: {
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      gap: 10,
      marginBottom: 12,
    },
  communityDetailSectionTitle: {
      color: TEXT,
      fontSize: 16,
      fontWeight: '800',
    },
  communityDetailActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
  communityDetailIconAction: {
      width: 68,
      height: 46,
      borderRadius: 14,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
    },
  communityDetailIconActionText: {
      color: TEXT_MUTED,
      fontSize: 9,
      fontWeight: '700',
    },
  communityDetailRunAction: {
      flex: 1,
      height: 46,
      borderRadius: 23,
      backgroundColor: GREEN,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 5,
    },
  communityActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
  communityIconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
    },
  communityRunButton: {
      flex: 1,
      height: 40,
      borderRadius: 20,
      backgroundColor: GREEN,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
  communityRunButtonText: {
      color: '#fff',
      fontSize: 12,
      fontWeight: '800',
    },
  communityStatusBox: {
      borderRadius: 14,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      marginBottom: 12,
    },
  communityStatusTitle: {
      color: TEXT,
      fontSize: 13,
      fontWeight: '800',
    },
  communityStatusText: {
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '600',
      lineHeight: 16,
      marginTop: 5,
    },
  communityEmptyBox: {
      minHeight: 120,
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 20,
    },
  communityEmptyTitle: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '700',
    },
  communityEmptyText: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 6,
    }
};
