import {GREEN, LINE, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const homeStyles = {
  homeScroll: {
      flex: 1,
      backgroundColor: SCREEN,
    },
  homeContent: {
      padding: 16,
      paddingBottom: 32,
    },
  homeHero: {
      minHeight: 420,
      borderRadius: 22,
      backgroundColor: '#101f31',
      padding: 20,
      marginBottom: 18,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 18},
      shadowOpacity: 0.34,
      shadowRadius: 30,
      elevation: 10,
    },
  heroShadePanel: {
      position: 'absolute',
      left: -44,
      bottom: -36,
      width: 310,
      height: 150,
      borderRadius: 24,
      backgroundColor: 'rgba(28,47,71,0.7)',
      transform: [{rotate: '-10deg'}],
    },
  heroGlowOne: {
      position: 'absolute',
      right: -40,
      top: -32,
      width: 170,
      height: 170,
      borderRadius: 85,
      backgroundColor: 'rgba(94,203,250,0.14)',
    },
  heroGlowTwo: {
      position: 'absolute',
      right: 42,
      bottom: 92,
      width: 92,
      height: 92,
      borderRadius: 46,
      backgroundColor: 'rgba(16,201,124,0.12)',
    },
  heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
  heroKicker: {
      color: '#5ECBFA',
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
  heroTitle: {
      maxWidth: 320,
      color: '#F0F4FF',
      fontSize: 30,
      lineHeight: 38,
      fontWeight: '900',
      marginTop: 8,
      letterSpacing: 0,
    },
  heroReason: {
      maxWidth: 330,
      color: '#8AA0BC',
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
      marginTop: 8,
    },
  heroSummaryRow: {
      minHeight: 76,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      marginTop: 18,
    },
  heroSummaryItem: {
      flex: 1,
      minWidth: 0,
    },
  heroSummaryLabel: {
      color: '#7A92B0',
      fontSize: 9,
      fontWeight: '900',
      letterSpacing: 0.7,
      marginBottom: 7,
    },
  heroSummaryValue: {
      color: '#F0F4FF',
      fontSize: 14,
      fontWeight: '900',
    },
  heroSummaryDivider: {
      width: 1,
      height: 42,
      backgroundColor: 'rgba(255,255,255,0.08)',
      marginHorizontal: 10,
    },
  heroRouteCard: {
      minHeight: 158,
      borderRadius: 18,
      backgroundColor: 'rgba(8,18,31,0.78)',
      borderWidth: 1,
      borderColor: 'rgba(94,203,250,0.16)',
      padding: 16,
      marginTop: 14,
      flexDirection: 'row',
      gap: 14,
    },
  heroRouteInfo: {
      flex: 1,
      justifyContent: 'center',
    },
  heroStatRow: {
      flexDirection: 'row',
      gap: 6,
    },
  heroStatPill: {
      flex: 1,
      minHeight: 56,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.06)',
      paddingHorizontal: 8,
      paddingVertical: 9,
      justifyContent: 'center',
    },
  heroStatLabel: {
      color: '#7A92B0',
      fontSize: 9,
      fontWeight: '700',
      marginBottom: 5,
      letterSpacing: 0.3,
    },
  heroStatValue: {
      color: '#F0F4FF',
      fontSize: 13,
      fontWeight: '800',
    },
  heroRouteHint: {
      color: '#A8BFDB',
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 10,
    },
  heroBottomRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 16,
      gap: 12,
    },
  heroRouteName: {
      color: '#F0F4FF',
      fontSize: 14,
      fontWeight: '700',
    },
  heroRouteMeta: {
      color: '#7A92B0',
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 4,
    },
  heroButton: {
      minWidth: 112,
      height: 46,
      borderRadius: 23,
      backgroundColor: GREEN,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingHorizontal: 18,
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.32,
      shadowRadius: 14,
      elevation: 6,
    },
  heroButtonText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '800',
    },
  quickPromptBox: {
      height: 50,
      borderRadius: 14,
      backgroundColor: '#0E1928',
      borderWidth: 1,
      borderColor: 'rgba(94,203,250,0.16)',
      justifyContent: 'center',
      paddingHorizontal: 14,
      marginBottom: 12,
    },
  quickPromptInput: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
      padding: 0,
    },
  quickWheelContent: {
      gap: 8,
      paddingRight: 4,
      marginBottom: 12,
    },
  quickWheelItem: {
      height: 36,
      minWidth: 72,
      borderRadius: 18,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
  quickWheelItemActive: {
      backgroundColor: GREEN,
      borderColor: GREEN,
    },
  quickWheelText: {
      color: TEXT_MUTED,
      fontSize: 13,
      fontWeight: '700',
    },
  quickWheelTextActive: {
      color: '#fff',
    },
  quickDistanceRow: {
      flexDirection: 'row',
      gap: 8,
    },
  quickDistance: {
      flex: 1,
      height: 42,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
    },
  quickDistanceActive: {
      backgroundColor: 'rgba(75,132,243,0.18)',
      borderColor: GREEN,
    },
  quickDistanceText: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '700',
    },
  quickDistanceTextActive: {
      color: '#A8C6FC',
    },
  sectionHeaderInline: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      marginTop: 2,
    },
  homeSectionTitle: {
      color: TEXT,
      fontSize: 17,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
  homeSectionLink: {
      color: '#5ECBFA',
      fontSize: 12,
      fontWeight: '700',
    },
  popularRouteScroller: {
      gap: 12,
      paddingRight: 16,
      paddingBottom: 4,
    },
  popularRouteCard: {
      width: 246,
      minHeight: 170,
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      marginBottom: 8,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 5,
    },
  popularLocationPill: {
      height: 30,
      borderRadius: 15,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 5,
      marginBottom: 14,
    },
  popularLocationPillText: {
      color: '#5ECBFA',
      fontSize: 11,
      fontWeight: '800',
    },
  popularRouteBody: {
      flex: 1,
    },
  popularTitle: {
      color: TEXT,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: 0,
    },
  popularLocation: {
      color: '#5ECBFA',
      fontSize: 11,
      fontWeight: '700',
      marginTop: 4,
    },
  popularSub: {
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 4,
    },
  popularUserRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginTop: 10,
    },
  popularAvatar: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  popularAvatarText: {
      color: '#fff',
      fontSize: 9,
      fontWeight: '800',
    },
  popularUser: {
      color: '#A8BFDB',
      fontSize: 11,
      fontWeight: '600',
    }
};
