import {GREEN, LINE, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const homeStyles = {
  homeScroll: {
      flex: 1,
      backgroundColor: SCREEN,
    },
  homeContent: {
      padding: 16,
      paddingBottom: 32,
    },
  homeHero: {
      minHeight: 340,
      borderRadius: 20,
      backgroundColor: '#162638',
      padding: 20,
      marginBottom: 14,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 16},
      shadowOpacity: 0.32,
      shadowRadius: 28,
      elevation: 8,
    },
  heroShadePanel: {
      position: 'absolute',
      left: -60,
      bottom: -48,
      width: 260,
      height: 130,
      borderRadius: 20,
      backgroundColor: 'rgba(10,20,35,0.5)',
      transform: [{rotate: '-12deg'}],
    },
  heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
    },
  heroKicker: {
      color: '#5ECBFA',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  heroTitle: {
      width: 228,
      color: '#F0F4FF',
      fontSize: 28,
      lineHeight: 36,
      fontWeight: '800',
      marginTop: 8,
      letterSpacing: -0.3,
    },
  heroReason: {
      width: 242,
      color: '#8AA0BC',
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
      marginTop: 8,
    },
  heroRouteCard: {
      minHeight: 126,
      borderRadius: 14,
      backgroundColor: 'rgba(10,20,35,0.6)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.07)',
      padding: 14,
      marginTop: 18,
      flexDirection: 'row',
      gap: 14,
    },
  heroMapPreview: {
      width: 92,
      borderRadius: 12,
      backgroundColor: '#111827',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
  previewImage: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      width: '100%',
      height: '100%',
    },
  previewScrim: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(10,20,35,0.28)',
    },
  previewBadge: {
      position: 'absolute',
      left: 8,
      bottom: 8,
      minWidth: 40,
      height: 22,
      borderRadius: 11,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
  previewBadgeText: {
      color: '#fff',
      fontSize: 10,
      fontWeight: '700',
    },
  heroRouteInfo: {
      flex: 1,
      justifyContent: 'center',
    },
  heroStatRow: {
      flexDirection: 'row',
      gap: 6,
    },
  heroStatPill: {
      flex: 1,
      minHeight: 56,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.06)',
      paddingHorizontal: 8,
      paddingVertical: 9,
      justifyContent: 'center',
    },
  heroStatLabel: {
      color: '#7A92B0',
      fontSize: 9,
      fontWeight: '700',
      marginBottom: 5,
      letterSpacing: 0.3,
    },
  heroStatValue: {
      color: '#F0F4FF',
      fontSize: 13,
      fontWeight: '800',
    },
  heroRouteHint: {
      color: '#A8BFDB',
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 10,
    },
  routePreviewStack: {
      height: 122,
      marginTop: 16,
    },
  routePreviewBack: {
      position: 'absolute',
      right: 14,
      top: 28,
      width: 210,
      height: 82,
      borderRadius: 12,
      backgroundColor: '#0E1928',
      opacity: 0.75,
      transform: [{rotate: '-8deg'}],
    },
  routePreviewMid: {
      position: 'absolute',
      right: 34,
      top: 12,
      width: 214,
      height: 88,
      borderRadius: 12,
      backgroundColor: '#1C2F47',
      transform: [{rotate: '-8deg'}],
    },
  routePreviewFront: {
      position: 'absolute',
      right: 54,
      top: 0,
      width: 220,
      height: 96,
      borderRadius: 12,
      backgroundColor: '#D6E4FF',
      padding: 14,
      transform: [{rotate: '-8deg'}],
    },
  routePreviewShape: {
      position: 'absolute',
      right: 18,
      top: 16,
      color: '#3B72F0',
      fontSize: 38,
      fontWeight: '900',
    },
  routeLineOne: {
      width: 102,
      height: 7,
      borderRadius: 4,
      backgroundColor: '#7EA7F8',
      marginTop: 12,
    },
  routeLineTwo: {
      width: 72,
      height: 7,
      borderRadius: 4,
      backgroundColor: '#A8C4FC',
      marginTop: 10,
    },
  routeLineThree: {
      width: 126,
      height: 7,
      borderRadius: 4,
      backgroundColor: '#C8DCFE',
      marginTop: 10,
    },
  heroBottomRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 16,
      gap: 12,
    },
  heroRouteName: {
      color: '#F0F4FF',
      fontSize: 14,
      fontWeight: '700',
    },
  heroRouteMeta: {
      color: '#7A92B0',
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 4,
    },
  heroButton: {
      minWidth: 90,
      height: 40,
      borderRadius: 20,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
    },
  heroButtonText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '800',
    },
  quickCreateCard: {
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      marginBottom: 16,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 5,
    },
  quickCreateHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 14,
    },
  quickCreateKicker: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  quickCreateTitle: {
      color: TEXT,
      fontSize: 17,
      fontWeight: '800',
      marginTop: 4,
      letterSpacing: -0.2,
    },
  quickCreateIcon: {
      width: 42,
      height: 42,
      borderRadius: 14,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
    },
  quickPromptBox: {
      height: 46,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      justifyContent: 'center',
      paddingHorizontal: 14,
      marginBottom: 12,
    },
  quickPromptInput: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
      padding: 0,
    },
  quickWheelContent: {
      gap: 8,
      paddingRight: 4,
      marginBottom: 12,
    },
  quickWheelItem: {
      height: 36,
      minWidth: 72,
      borderRadius: 18,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
  quickWheelItemActive: {
      backgroundColor: GREEN,
      borderColor: GREEN,
    },
  quickWheelText: {
      color: TEXT_MUTED,
      fontSize: 13,
      fontWeight: '700',
    },
  quickWheelTextActive: {
      color: '#fff',
    },
  quickDistanceRow: {
      flexDirection: 'row',
      gap: 8,
    },
  quickDistance: {
      width: 58,
      height: 40,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
    },
  quickDistanceActive: {
      backgroundColor: 'rgba(75,132,243,0.18)',
      borderColor: GREEN,
    },
  quickDistanceText: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '700',
    },
  quickDistanceTextActive: {
      color: '#A8C6FC',
    },
  quickGenerateButton: {
      flex: 1,
      height: 40,
      borderRadius: 20,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  quickGenerateText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '800',
    },
  sectionHeaderInline: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
  homeSectionTitle: {
      color: TEXT,
      fontSize: 17,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
  homeSectionLink: {
      color: '#5ECBFA',
      fontSize: 12,
      fontWeight: '700',
    },
  popularRouteScroller: {
      gap: 12,
      paddingRight: 16,
      paddingBottom: 4,
    },
  popularRouteCard: {
      width: 274,
      minHeight: 210,
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
      marginBottom: 8,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 5,
    },
  popularMapPreview: {
      height: 106,
      borderRadius: 12,
      backgroundColor: '#111827',
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
  popularImageLabel: {
      position: 'absolute',
      left: 10,
      top: 10,
      height: 24,
      borderRadius: 12,
      backgroundColor: 'rgba(14,25,40,0.82)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
  popularImageLabelText: {
      color: '#fff',
      fontSize: 10,
      fontWeight: '700',
    },
  popularRouteBody: {
      flex: 1,
    },
  popularTitle: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
  popularLocation: {
      color: '#5ECBFA',
      fontSize: 11,
      fontWeight: '700',
      marginTop: 4,
    },
  popularSub: {
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 4,
    },
  popularUserRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      marginTop: 10,
    },
  popularAvatar: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  popularAvatarText: {
      color: '#fff',
      fontSize: 9,
      fontWeight: '800',
    },
  popularUser: {
      color: '#A8BFDB',
      fontSize: 11,
      fontWeight: '600',
    }
};
