import {GREEN, LINE, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const profileStyles = {
  profileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      marginBottom: 14,
      minHeight: 130,
      borderRadius: 20,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 20,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 12},
      shadowOpacity: 0.24,
      shadowRadius: 24,
      elevation: 8,
    },
  avatar: {
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 4,
    },
  avatarText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: '800',
    },
  profileName: {
      color: TEXT,
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
    },
  profileHeaderCopy: {
      flex: 1,
    },
  profileSub: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 4,
    },
  profileAccountCard: {
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      marginBottom: 12,
      gap: 12,
    },
  profileSectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
  profileSectionTitle: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '800',
    },
  profileStatusPill: {
      height: 26,
      borderRadius: 13,
      backgroundColor: 'rgba(16,201,124,0.14)',
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
  profileStatusText: {
      color: '#6EE7B7',
      fontSize: 10,
      fontWeight: '700',
    },
  profileInfoRow: {
      minHeight: 50,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
  profileInfoCopy: {
      flex: 1,
    },
  profileInfoLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
  profileInfoValue: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
      marginTop: 3,
    },
  profileDangerCard: {
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      gap: 10,
      marginTop: 4,
    },
  profileLogoutButton: {
      height: 46,
      borderRadius: 23,
      backgroundColor: 'rgba(75,132,243,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(75,132,243,0.25)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
  profileLogoutText: {
      color: '#A8C6FC',
      fontSize: 13,
      fontWeight: '700',
    },
  profileDeleteButton: {
      height: 46,
      borderRadius: 23,
      backgroundColor: 'rgba(239,68,68,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(239,68,68,0.22)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
  profileDeleteText: {
      color: '#FCA5A5',
      fontSize: 13,
      fontWeight: '700',
    },
  profileRunEntryCard: {
      minHeight: 104,
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 5,
    },
  profileRunEntryIcon: {
      width: 54,
      height: 54,
      borderRadius: 27,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 7},
      shadowOpacity: 0.32,
      shadowRadius: 14,
      elevation: 5,
    },
  profileRunEntryTitle: {
      color: TEXT,
      fontSize: 17,
      fontWeight: '800',
      letterSpacing: -0.2,
    },
  profileRunEntrySub: {
      color: TEXT_MUTED,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '600',
      marginTop: 5,
    },
  profileRunEntryMetaRow: {
      alignSelf: 'flex-start',
      minHeight: 26,
      borderRadius: 13,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 10,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
    },
  profileRunEntryMeta: {
    color: '#A8C6FC',
    fontSize: 10,
    fontWeight: '700',
  },
  profileLikedEntryCard: {
    minHeight: 96,
    borderRadius: 18,
    backgroundColor: '#182A3D',
    borderWidth: 1,
    borderColor: 'rgba(248,113,113,0.22)',
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 5,
  },
  profileLikedEntryIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#F43F5E',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F43F5E',
    shadowOffset: {width: 0, height: 7},
    shadowOpacity: 0.32,
    shadowRadius: 14,
    elevation: 5,
  },
  profileLikedMetaRow: {
    alignSelf: 'flex-start',
    minHeight: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(244,63,94,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(244,63,94,0.22)',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  profileLikedMeta: {
    color: '#FDA4AF',
    fontSize: 10,
    fontWeight: '700',
  },
  profileRunListSummary: {
      minHeight: 92,
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      marginBottom: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
  profileRunListIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: GREEN,
      alignItems: 'center',
    justifyContent: 'center',
  },
  profileLikedListIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#F43F5E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileRunListTitle: {
      color: TEXT,
      fontSize: 18,
      fontWeight: '800',
    },
  profileRunListSub: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 5,
    },
  profileRunRecordCard: {
      minHeight: 72,
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.14,
      shadowRadius: 14,
      elevation: 4,
  },
  profileLikedBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#F43F5E',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F43F5E',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 4,
  },
  profileRunSharePill: {
      height: 30,
      minWidth: 52,
      borderRadius: 15,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 10,
    },
  profileRunSharePillActive: {
      backgroundColor: 'rgba(16,201,124,0.14)',
      borderColor: 'rgba(16,201,124,0.35)',
    },
  profileRunShareText: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
    },
  profileRunShareTextActive: {
      color: '#6EE7B7',
    },
  profileRunDetailHero: {
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 22,
      marginBottom: 12,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 10},
      shadowOpacity: 0.2,
      shadowRadius: 20,
      elevation: 6,
    },
  profileRunDetailBadge: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.38,
      shadowRadius: 16,
      elevation: 5,
    },
  profileRunDetailTitle: {
      color: TEXT,
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: -0.4,
    },
  profileRunDetailSub: {
      color: TEXT_MUTED,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      marginTop: 7,
    }
};
