import {BLUE, GREEN, LINE, RUN_GREEN, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const runStyles = {
  navigationSheetLayer: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      zIndex: 8,
      elevation: 8,
    },
  panelScroll: {
      flex: 1,
      backgroundColor: SCREEN,
    },
  navigationPanelScroll: {
      backgroundColor: 'transparent',
    },
  panelContent: {
      padding: 18,
      paddingBottom: 18,
    },
  navigationPanelContent: {
      flexGrow: 1,
      paddingHorizontal: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  navigationSheetHost: {
      flex: 1,
      backgroundColor: 'transparent',
    },
  runBottomSheet: {
      flex: 1,
      flexGrow: 1,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      overflow: 'hidden',
      backgroundColor: SCREEN,
      borderTopWidth: 1,
      borderColor: LINE,
      paddingHorizontal: 18,
      paddingTop: 6,
      paddingBottom: 24,
      marginTop: 0,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: -10},
      shadowOpacity: 0.22,
      shadowRadius: 24,
      elevation: 10,
      zIndex: 5,
    },
  sheetScrollBody: {
      flex: 1,
    },
  sheetScrollContent: {
      paddingBottom: 24,
    },
  sheetDragHandleArea: {
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
  sheetDragHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: LINE,
    },
  sheetHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
  sheetHeaderButton: {
      height: 34,
      minWidth: 52,
      borderRadius: 17,
      backgroundColor: SURFACE_2,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 14,
    },
  sheetHeaderButtonText: {
      color: TEXT,
      fontSize: 12,
      fontWeight: '700',
    },
  runSetupCard: {
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 16,
      marginBottom: 14,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.2,
      shadowRadius: 18,
      elevation: 5,
    },
  runSetupHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 14,
    },
  runSetupKicker: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  runSetupTitle: {
      color: TEXT,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '800',
      marginTop: 4,
      letterSpacing: -0.2,
    },
  runSetupBadge: {
      minWidth: 72,
      height: 32,
      borderRadius: 16,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
  runSetupBadgeText: {
      color: '#fff',
      fontSize: 11,
      fontWeight: '800',
    },
  runSetupGrid: {
      flexDirection: 'row',
      gap: 8,
    },
  runSetupMetric: {
      flex: 1,
      minHeight: 64,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      padding: 12,
      justifyContent: 'center',
    },
  runSetupMetricLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      marginBottom: 5,
      letterSpacing: 0.3,
    },
  runSetupMetricValue: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '800',
    },
  sectionHeader: {
      marginBottom: 14,
    },
  sectionTitle: {
      fontSize: 19,
      fontWeight: '800',
      color: TEXT,
      letterSpacing: -0.2,
    },
  sectionMeta: {
      marginTop: 4,
      fontSize: 12,
      fontWeight: '600',
      color: TEXT_MUTED,
    },
  inputBlock: {
      marginBottom: 12,
    },
  inputLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: TEXT_MUTED,
      marginBottom: 7,
      letterSpacing: 0.3,
    },
  textInput: {
      minHeight: 48,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: LINE,
      backgroundColor: SURFACE,
      paddingHorizontal: 14,
      color: TEXT,
      fontSize: 15,
      fontWeight: '600',
    },
  chipRow: {
      gap: 8,
      paddingRight: 8,
      marginBottom: 14,
    },
  shapeChip: {
      minWidth: 132,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: LINE,
      backgroundColor: SURFACE,
      padding: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
  shapeChipActive: {
      borderColor: GREEN,
      backgroundColor: 'rgba(75,132,243,0.12)',
    },
  shapeIconBox: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      borderWidth: 1,
      borderColor: LINE,
      alignItems: 'center',
      justifyContent: 'center',
    },
  shapeIconBoxActive: {
      backgroundColor: 'rgba(75,132,243,0.2)',
      borderColor: 'rgba(75,132,243,0.4)',
    },
  shapeChipCopy: {
      flex: 1,
    },
  shapeChipText: {
      fontSize: 14,
      fontWeight: '700',
      color: TEXT,
    },
  shapeChipHint: {
      marginTop: 2,
      fontSize: 10,
      fontWeight: '600',
      color: TEXT_MUTED,
    },
  shapeChipTextActive: {
      color: '#A8C6FC',
    },
  gridTwo: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 8,
    },
  metricCard: {
      flex: 1,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: LINE,
      backgroundColor: SURFACE,
      padding: 14,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.14,
      shadowRadius: 14,
      elevation: 4,
    },
  metricLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
  metricValue: {
      marginTop: 5,
      color: TEXT,
      fontSize: 22,
      fontWeight: '800',
    },
  slider: {
      width: '100%',
      height: 34,
      marginBottom: 4,
    },
  segmented: {
      flexDirection: 'row',
      backgroundColor: SURFACE_2,
      borderRadius: 14,
      padding: 3,
      marginTop: 4,
      marginBottom: 12,
    },
  segment: {
      flex: 1,
      height: 36,
      borderRadius: 11,
      alignItems: 'center',
      justifyContent: 'center',
    },
  segmentActive: {
      backgroundColor: GREEN,
    },
  segmentText: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '700',
    },
  segmentTextActive: {
      color: '#fff',
    },
  optionList: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: LINE,
      backgroundColor: SURFACE,
      marginBottom: 12,
    },
  locationButton: {
      minHeight: 56,
      borderRadius: 14,
      backgroundColor: 'rgba(75,132,243,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(75,132,243,0.3)',
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 12,
    },
  locationIconBox: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: 'rgba(75,132,243,0.2)',
      alignItems: 'center',
      justifyContent: 'center',
    },
  locationTextBox: {
      flex: 1,
    },
  locationTitle: {
      color: TEXT,
      fontSize: 13,
      fontWeight: '700',
    },
  locationSub: {
      marginTop: 2,
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '600',
      fontVariant: ['tabular-nums'],
    },
  actionRow: {
      flexDirection: 'row',
      gap: 10,
    },
  runHero: {
      borderRadius: 16,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 18,
      marginBottom: 12,
    },
  guidancePanel: {
      flexGrow: 1,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      overflow: 'hidden',
      backgroundColor: SCREEN,
      borderWidth: 1,
      borderColor: LINE,
      padding: 18,
      paddingTop: 6,
      paddingBottom: 24,
      marginTop: 0,
      marginBottom: 0,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: -10},
      shadowOpacity: 0.22,
      shadowRadius: 24,
      elevation: 10,
      zIndex: 5,
    },
  guidanceHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 16,
    },
  guidanceKicker: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  guidanceTitle: {
      color: TEXT,
      fontSize: 18,
      fontWeight: '800',
      marginTop: 4,
      letterSpacing: -0.2,
    },
  guidanceBadge: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: SURFACE_2,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: LINE,
    },
  guidanceBadgeText: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '800',
    },
  guidanceInstruction: {
      minHeight: 72,
      borderRadius: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: SURFACE,
      padding: 14,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: LINE,
    },
  guidanceInstructionIcon: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  guidanceInstructionTextBox: {
      flex: 1,
    },
  guidanceInstructionTitle: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '700',
    },
  guidanceInstructionSub: {
      color: TEXT_MUTED,
      fontSize: 11,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 4,
    },
  guidanceStats: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
    },
  guidanceStat: {
      flex: 1,
      minHeight: 62,
      borderRadius: 12,
      backgroundColor: SURFACE_2,
      padding: 12,
      justifyContent: 'center',
    },
  guidanceStatLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      marginBottom: 5,
      letterSpacing: 0.3,
    },
  guidanceStatValue: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '800',
    },
  guidanceVoice: {
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
  guidanceVoiceIcon: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  guidanceVoiceText: {
      flex: 1,
      color: TEXT,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
    },
  runningHudLayer: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
    paddingHorizontal: 14,
    paddingBottom: 74,
  },
  runningProgressPill: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(10,20,35,0.9)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.1)',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.22,
      shadowRadius: 16,
      elevation: 8,
    },
  runningProgressText: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '900',
    },
  runningFloatingCard: {
    borderRadius: 22,
    backgroundColor: 'rgba(8,18,31,0.94)',
      borderWidth: 1,
      borderColor: 'rgba(94,203,250,0.18)',
    padding: 12,
    gap: 10,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 16},
      shadowOpacity: 0.32,
      shadowRadius: 28,
      elevation: 12,
    },
  runningCardTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
  runningInstructionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 5,
    },
  runningInstructionCopy: {
      flex: 1,
    },
  runningKicker: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0.4,
    },
  runningTitle: {
    color: TEXT,
    fontSize: 18,
      fontWeight: '900',
      marginTop: 3,
      letterSpacing: -0.2,
    },
  runningSub: {
      color: TEXT_MUTED,
      fontSize: 12,
    lineHeight: 16,
      fontWeight: '600',
      marginTop: 4,
    },
  runningStatRow: {
      flexDirection: 'row',
      gap: 8,
    },
  runningStat: {
    flex: 1,
    minHeight: 58,
      borderRadius: 16,
      backgroundColor: 'rgba(75,132,243,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(125,174,252,0.16)',
      padding: 11,
      justifyContent: 'center',
    },
  runningStatLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '800',
      marginBottom: 6,
      letterSpacing: 0.2,
    },
  runningStatValue: {
      color: TEXT,
      fontSize: 16,
      fontWeight: '900',
    },
  runningVoiceCard: {
    minHeight: 44,
      borderRadius: 16,
      backgroundColor: 'rgba(255,255,255,0.06)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
  runningVoiceIcon: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
    },
  runningVoiceText: {
      flex: 1,
      color: TEXT,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700',
    },
  finishPanel: {
      flexGrow: 1,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      overflow: 'hidden',
      backgroundColor: SCREEN,
      borderWidth: 1,
      borderColor: LINE,
      padding: 22,
      paddingTop: 6,
      paddingBottom: 24,
      marginTop: 0,
      marginBottom: 0,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: -10},
      shadowOpacity: 0.22,
      shadowRadius: 24,
      elevation: 10,
      zIndex: 5,
    },
  finishIcon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: RUN_GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
      shadowColor: RUN_GREEN,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 6,
    },
  finishKicker: {
      color: '#5ECBFA',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  finishTitle: {
      color: TEXT,
      fontSize: 24,
      lineHeight: 31,
      fontWeight: '800',
      marginTop: 6,
      letterSpacing: -0.3,
    },
  finishSub: {
      color: TEXT_MUTED,
      fontSize: 13,
      lineHeight: 19,
      fontWeight: '600',
      marginTop: 7,
    },
  finishStats: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 18,
      marginBottom: 18,
    },
  finishStat: {
      flex: 1,
      minHeight: 66,
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
      justifyContent: 'center',
    },
  finishStatLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      marginBottom: 5,
      letterSpacing: 0.3,
    },
  finishStatValue: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '800',
    },
  shareCardSection: {
      borderRadius: 18,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      marginBottom: 16,
    },
  shareCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
  shareCardKicker: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
    },
  shareCardTitle: {
      color: TEXT,
      fontSize: 15,
      fontWeight: '800',
      marginTop: 3,
    },
  sharePreviewCard: {
      minHeight: 300,
      borderRadius: 18,
      backgroundColor: '#0A1423',
      borderWidth: 1,
      borderColor: 'rgba(94,203,250,0.22)',
      padding: 16,
      overflow: 'hidden',
    },
  sharePreviewTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
  sharePreviewBrand: {
      color: '#5ECBFA',
      fontSize: 12,
      fontWeight: '800',
    },
  sharePreviewName: {
      color: TEXT,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '900',
      marginTop: 4,
    },
  sharePreviewBadge: {
      height: 30,
      borderRadius: 15,
      backgroundColor: RUN_GREEN,
      paddingHorizontal: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
  sharePreviewBadgeText: {
      color: '#fff',
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0.5,
    },
  shareRoutePreview: {
      height: 132,
      borderRadius: 16,
      backgroundColor: '#102033',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      marginBottom: 14,
      overflow: 'hidden',
    },
  shareRouteMapImage: {
      width: '100%',
      height: '100%',
    },
  shareRouteMapFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      padding: 16,
    },
  shareRouteMapFallbackText: {
      color: '#A8BFDB',
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
    },
  shareMetricRow: {
      flexDirection: 'row',
      gap: 8,
    },
  shareMetric: {
      flex: 1,
      minHeight: 66,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.07)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
      padding: 10,
      justifyContent: 'center',
    },
  shareMetricLabel: {
      color: '#8AA0BC',
      fontSize: 9,
      fontWeight: '800',
      marginBottom: 5,
      letterSpacing: 0.5,
    },
  shareMetricValue: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '900',
    },
  sharePreviewFooter: {
      color: '#A8BFDB',
      fontSize: 11,
      fontWeight: '700',
      marginTop: 12,
    },
  shareSaveButton: {
      height: 48,
      borderRadius: 24,
      backgroundColor: BLUE,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginTop: 12,
      shadowColor: BLUE,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.32,
      shadowRadius: 14,
      elevation: 5,
    },
  shareSaveButtonDone: {
      backgroundColor: RUN_GREEN,
      shadowColor: RUN_GREEN,
    },
  shareSaveButtonText: {
      color: '#fff',
      fontSize: 14,
      fontWeight: '800',
    },
  finishActions: {
    flexDirection: 'row',
    gap: 10,
  },
  communityRegisterButton: {
    height: 52,
    borderRadius: 26,
    backgroundColor: RUN_GREEN,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
    shadowColor: RUN_GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.32,
    shadowRadius: 14,
    elevation: 5,
  },
  communityRegisterButtonDone: {
    backgroundColor: '#0EA66A',
    shadowColor: '#0EA66A',
  },
  communityRegisterButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  runState: {
      color: '#6EE7B7',
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
  runDistance: {
      color: TEXT,
      fontSize: 44,
      fontWeight: '900',
      marginTop: 8,
      letterSpacing: -1,
    },
  runTarget: {
      color: TEXT_MUTED,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 2,
    },
  progressTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: SURFACE_2,
      overflow: 'hidden',
      marginTop: 18,
    },
  progressFill: {
      height: '100%',
      borderRadius: 4,
      backgroundColor: RUN_GREEN,
    },
  gridThree: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 12,
    },
  liveCard: {
      flex: 1,
      borderRadius: 12,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 12,
    },
  liveLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
  liveValue: {
      color: TEXT,
      fontSize: 18,
      fontWeight: '800',
      marginTop: 5,
    },
  voiceCard: {
      borderRadius: 14,
      backgroundColor: 'rgba(75,132,243,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(75,132,243,0.25)',
      padding: 14,
      marginBottom: 12,
    },
  voiceLabel: {
      color: '#5ECBFA',
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
  voiceText: {
      color: TEXT,
      marginTop: 7,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 21,
    },
  musicCard: {
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
  musicTitle: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
    },
  musicSub: {
      color: TEXT_MUTED,
      fontSize: 11,
      fontWeight: '600',
      marginTop: 3,
    },
  musicBpm: {
      color: '#5ECBFA',
      fontSize: 16,
      fontWeight: '800',
    }
};
