import {GREEN, LINE, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from '../theme';

export const sharedStyles = {
  toggleRow: {
      minHeight: 50,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: LINE,
    },
  toggleLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: TEXT,
    },
  readyCard: {
      borderRadius: 14,
      backgroundColor: 'rgba(16,201,124,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(16,201,124,0.25)',
      padding: 16,
      marginBottom: 12,
    },
  readyTitle: {
      color: '#E0FFF4',
      fontSize: 15,
      fontWeight: '800',
    },
  readySub: {
      color: '#7DCEAE',
      marginTop: 4,
      fontSize: 12,
      fontWeight: '600',
    },
  readyStats: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 12,
    },
  readyStat: {
      overflow: 'hidden',
      color: '#A8F0D4',
      backgroundColor: 'rgba(16,201,124,0.16)',
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 10,
      fontSize: 12,
      fontWeight: '700',
    },
  primaryButton: {
      flex: 1,
      height: 52,
      borderRadius: 26,
      backgroundColor: GREEN,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: GREEN,
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    },
  primaryButtonText: {
      color: '#fff',
      fontSize: 15,
      fontWeight: '800',
    },
  secondaryButton: {
      width: 100,
      height: 52,
      borderRadius: 26,
      backgroundColor: SURFACE_2,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: LINE,
    },
  secondaryButtonText: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
    },
  buttonDisabled: {
      opacity: 0.4,
    },
  secondaryButtonFlex: {
      flex: 1,
      height: 52,
      borderRadius: 26,
      backgroundColor: SURFACE_2,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: LINE,
    },
  listTitle: {
      color: TEXT,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 10,
    },
  runCard: {
      minHeight: 70,
      borderRadius: 14,
      backgroundColor: SURFACE,
      borderWidth: 1,
      borderColor: LINE,
      padding: 14,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 4,
    },
  runBadge: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: 'rgba(75,132,243,0.15)',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'rgba(75,132,243,0.3)',
    },
  runBadgeText: {
      color: '#7DAEFC',
      fontSize: 18,
      fontWeight: '800',
    },
  runCardBody: {
      flex: 1,
    },
  runCardTitle: {
      color: TEXT,
      fontSize: 14,
      fontWeight: '700',
    },
  runCardSub: {
      color: TEXT_MUTED,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 3,
    },
  smallButton: {
      minWidth: 58,
      height: 32,
      borderRadius: 16,
      backgroundColor: SURFACE_2,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: LINE,
    },
  smallButtonText: {
      color: TEXT,
      fontSize: 12,
      fontWeight: '700',
    },
  footer: {
      minHeight: 66,
      paddingTop: 8,
      paddingHorizontal: 10,
      backgroundColor: SURFACE,
      borderTopWidth: 1,
      borderTopColor: LINE,
      flexDirection: 'row',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: -6},
      shadowOpacity: 0.2,
      shadowRadius: 16,
      elevation: 10,
      zIndex: 20,
    },
  footerItem: {
      flex: 1,
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderRadius: 14,
      marginHorizontal: 3,
    },
  footerItemActive: {
      backgroundColor: 'rgba(75,132,243,0.12)',
    },
  footerLabel: {
      color: TEXT_MUTED,
      fontSize: 10,
      fontWeight: '700',
    },
  footerActive: {
      color: GREEN,
    }
};
