import {Platform, StyleSheet} from 'react-native';
import {GREEN, LINE, RUN_GREEN, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from './theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  header: {
    height: 62,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: SCREEN,
  },
  brand: {
    fontSize: 24,
    fontWeight: '900',
    color: TEXT,
    letterSpacing: -0.5,
  },
  brandSub: {
    fontSize: 10,
    fontWeight: '600',
    color: TEXT_MUTED,
    marginTop: 1,
    letterSpacing: 0.2,
  },
  headerPill: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerPillText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  mapShell: {
    height: Platform.OS === 'ios' ? 255 : 245,
    marginHorizontal: 16,
    marginBottom: 14,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: SURFACE,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 8,
  },
  navigationMapShell: {
    height: Platform.OS === 'ios' ? 470 : 450,
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
    zIndex: 0,
  },
  navigationMapFull: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    height: undefined,
  },
  webview: {
    flex: 1,
    backgroundColor: '#e5e7eb',
  },
  mapOverlay: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(14,25,40,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  mapTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  mapSub: {
    marginTop: 3,
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '600',
  },
  navigationBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 16,
    minHeight: 60,
    borderRadius: 16,
    backgroundColor: GREEN,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 8,
  },
  navigationBannerIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationBannerTextBox: {
    flex: 1,
  },
  navigationBannerTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  navigationBannerSub: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  navigationPacePill: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(14,25,40,0.88)',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  navigationPaceText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(14,25,40,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingCard: {
    minWidth: 140,
    alignItems: 'center',
    gap: 12,
    padding: 22,
    borderRadius: 20,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
  },
  loadingText: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '700',
  },
  contentShell: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  runNavigationStage: {
    flex: 1,
    backgroundColor: SCREEN,
    overflow: 'hidden',
  },
  navigationContentShell: {
    backgroundColor: 'transparent',
    marginTop: 0,
    zIndex: 3,
    elevation: 3,
  },
  navigationSheetLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 8,
    elevation: 8,
  },
  homeScroll: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  homeContent: {
    padding: 16,
    paddingBottom: 32,
  },
  homeHero: {
    minHeight: 340,
    borderRadius: 20,
    backgroundColor: '#162638',
    padding: 20,
    marginBottom: 14,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 16},
    shadowOpacity: 0.32,
    shadowRadius: 28,
    elevation: 8,
  },
  heroShadePanel: {
    position: 'absolute',
    left: -60,
    bottom: -48,
    width: 260,
    height: 130,
    borderRadius: 20,
    backgroundColor: 'rgba(10,20,35,0.5)',
    transform: [{rotate: '-12deg'}],
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroKicker: {
    color: '#5ECBFA',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  heroTitle: {
    width: 228,
    color: '#F0F4FF',
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '800',
    marginTop: 8,
    letterSpacing: -0.3,
  },
  heroReason: {
    width: 242,
    color: '#8AA0BC',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '600',
    marginTop: 8,
  },
  heroRouteCard: {
    minHeight: 126,
    borderRadius: 14,
    backgroundColor: 'rgba(10,20,35,0.6)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 14,
    marginTop: 18,
    flexDirection: 'row',
    gap: 14,
  },
  heroMapPreview: {
    width: 92,
    borderRadius: 12,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  previewImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  previewScrim: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10,20,35,0.28)',
  },
  previewBadge: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    minWidth: 40,
    height: 22,
    borderRadius: 11,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  previewBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },
  heroRouteInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  heroStatRow: {
    flexDirection: 'row',
    gap: 6,
  },
  heroStatPill: {
    flex: 1,
    minHeight: 56,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 8,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  heroStatLabel: {
    color: '#7A92B0',
    fontSize: 9,
    fontWeight: '700',
    marginBottom: 5,
    letterSpacing: 0.3,
  },
  heroStatValue: {
    color: '#F0F4FF',
    fontSize: 13,
    fontWeight: '800',
  },
  heroRouteHint: {
    color: '#A8BFDB',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 10,
  },
  routePreviewStack: {
    height: 122,
    marginTop: 16,
  },
  routePreviewBack: {
    position: 'absolute',
    right: 14,
    top: 28,
    width: 210,
    height: 82,
    borderRadius: 12,
    backgroundColor: '#0E1928',
    opacity: 0.75,
    transform: [{rotate: '-8deg'}],
  },
  routePreviewMid: {
    position: 'absolute',
    right: 34,
    top: 12,
    width: 214,
    height: 88,
    borderRadius: 12,
    backgroundColor: '#1C2F47',
    transform: [{rotate: '-8deg'}],
  },
  routePreviewFront: {
    position: 'absolute',
    right: 54,
    top: 0,
    width: 220,
    height: 96,
    borderRadius: 12,
    backgroundColor: '#D6E4FF',
    padding: 14,
    transform: [{rotate: '-8deg'}],
  },
  routePreviewShape: {
    position: 'absolute',
    right: 18,
    top: 16,
    color: '#3B72F0',
    fontSize: 38,
    fontWeight: '900',
  },
  routeLineOne: {
    width: 102,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#7EA7F8',
    marginTop: 12,
  },
  routeLineTwo: {
    width: 72,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#A8C4FC',
    marginTop: 10,
  },
  routeLineThree: {
    width: 126,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#C8DCFE',
    marginTop: 10,
  },
  heroBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 12,
  },
  heroRouteName: {
    color: '#F0F4FF',
    fontSize: 14,
    fontWeight: '700',
  },
  heroRouteMeta: {
    color: '#7A92B0',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 4,
  },
  heroButton: {
    minWidth: 90,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  heroButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  quickCreateCard: {
    borderRadius: 18,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 5,
  },
  quickCreateHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  quickCreateKicker: {
    color: '#5ECBFA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  quickCreateTitle: {
    color: TEXT,
    fontSize: 17,
    fontWeight: '800',
    marginTop: 4,
    letterSpacing: -0.2,
  },
  quickCreateIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickPromptBox: {
    height: 46,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  quickPromptInput: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
    padding: 0,
  },
  quickWheelContent: {
    gap: 8,
    paddingRight: 4,
    marginBottom: 12,
  },
  quickWheelItem: {
    height: 36,
    minWidth: 72,
    borderRadius: 18,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  quickWheelItemActive: {
    backgroundColor: GREEN,
    borderColor: GREEN,
  },
  quickWheelText: {
    color: TEXT_MUTED,
    fontSize: 13,
    fontWeight: '700',
  },
  quickWheelTextActive: {
    color: '#fff',
  },
  quickDistanceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quickDistance: {
    width: 58,
    height: 40,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickDistanceActive: {
    backgroundColor: 'rgba(75,132,243,0.18)',
    borderColor: GREEN,
  },
  quickDistanceText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
  },
  quickDistanceTextActive: {
    color: '#A8C6FC',
  },
  quickGenerateButton: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickGenerateText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  sectionHeaderInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  homeSectionTitle: {
    color: TEXT,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  homeSectionLink: {
    color: '#5ECBFA',
    fontSize: 12,
    fontWeight: '700',
  },
  popularRouteScroller: {
    gap: 12,
    paddingRight: 16,
    paddingBottom: 4,
  },
  popularRouteCard: {
    width: 274,
    minHeight: 210,
    borderRadius: 18,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 5,
  },
  popularMapPreview: {
    height: 106,
    borderRadius: 12,
    backgroundColor: '#111827',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  popularImageLabel: {
    position: 'absolute',
    left: 10,
    top: 10,
    height: 24,
    borderRadius: 12,
    backgroundColor: 'rgba(14,25,40,0.82)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  popularImageLabelText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },
  popularRouteBody: {
    flex: 1,
  },
  popularTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  popularLocation: {
    color: '#5ECBFA',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  popularSub: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 4,
  },
  popularUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 10,
  },
  popularAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  popularAvatarText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '800',
  },
  popularUser: {
    color: '#A8BFDB',
    fontSize: 11,
    fontWeight: '600',
  },
  panelScroll: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  navigationPanelScroll: {
    backgroundColor: 'transparent',
  },
  panelContent: {
    padding: 18,
    paddingBottom: 18,
  },
  navigationPanelContent: {
    flexGrow: 1,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  navigationSheetHost: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  runBottomSheet: {
    flex: 1,
    flexGrow: 1,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
    backgroundColor: SCREEN,
    borderTopWidth: 1,
    borderColor: LINE,
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 24,
    marginTop: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -10},
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 10,
    zIndex: 5,
  },
  sheetScrollBody: {
    flex: 1,
  },
  sheetScrollContent: {
    paddingBottom: 24,
  },
  sheetDragHandleArea: {
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  sheetDragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: LINE,
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sheetHeaderButton: {
    height: 34,
    minWidth: 52,
    borderRadius: 17,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  sheetHeaderButtonText: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '700',
  },
  runSetupCard: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 16,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.2,
    shadowRadius: 18,
    elevation: 5,
  },
  runSetupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  runSetupKicker: {
    color: '#5ECBFA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  runSetupTitle: {
    color: TEXT,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    marginTop: 4,
    letterSpacing: -0.2,
  },
  runSetupBadge: {
    minWidth: 72,
    height: 32,
    borderRadius: 16,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  runSetupBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },
  runSetupGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  runSetupMetric: {
    flex: 1,
    minHeight: 64,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    padding: 12,
    justifyContent: 'center',
  },
  runSetupMetricLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 5,
    letterSpacing: 0.3,
  },
  runSetupMetricValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '800',
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: TEXT,
    letterSpacing: -0.2,
  },
  sectionMeta: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
    color: TEXT_MUTED,
  },
  inputBlock: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: TEXT_MUTED,
    marginBottom: 7,
    letterSpacing: 0.3,
  },
  textInput: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    paddingHorizontal: 14,
    color: TEXT,
    fontSize: 15,
    fontWeight: '600',
  },
  chipRow: {
    gap: 8,
    paddingRight: 8,
    marginBottom: 14,
  },
  shapeChip: {
    minWidth: 132,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  shapeChipActive: {
    borderColor: GREEN,
    backgroundColor: 'rgba(75,132,243,0.12)',
  },
  shapeIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shapeIconBoxActive: {
    backgroundColor: 'rgba(75,132,243,0.2)',
    borderColor: 'rgba(75,132,243,0.4)',
  },
  shapeChipCopy: {
    flex: 1,
  },
  shapeChipText: {
    fontSize: 14,
    fontWeight: '700',
    color: TEXT,
  },
  shapeChipHint: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '600',
    color: TEXT_MUTED,
  },
  shapeChipTextActive: {
    color: '#A8C6FC',
  },
  gridTwo: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  metricCard: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 4,
  },
  metricLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  metricValue: {
    marginTop: 5,
    color: TEXT,
    fontSize: 22,
    fontWeight: '800',
  },
  slider: {
    width: '100%',
    height: 34,
    marginBottom: 4,
  },
  segmented: {
    flexDirection: 'row',
    backgroundColor: SURFACE_2,
    borderRadius: 14,
    padding: 3,
    marginTop: 4,
    marginBottom: 12,
  },
  segment: {
    flex: 1,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: GREEN,
  },
  segmentText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
  },
  segmentTextActive: {
    color: '#fff',
  },
  optionList: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    marginBottom: 12,
  },
  toggleRow: {
    minHeight: 50,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: LINE,
  },
  toggleLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: TEXT,
  },
  locationButton: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: 'rgba(75,132,243,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(75,132,243,0.3)',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  locationIconBox: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(75,132,243,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationTextBox: {
    flex: 1,
  },
  locationTitle: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '700',
  },
  locationSub: {
    marginTop: 2,
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  readyCard: {
    borderRadius: 14,
    backgroundColor: 'rgba(16,201,124,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(16,201,124,0.25)',
    padding: 16,
    marginBottom: 12,
  },
  readyTitle: {
    color: '#E0FFF4',
    fontSize: 15,
    fontWeight: '800',
  },
  readySub: {
    color: '#7DCEAE',
    marginTop: 4,
    fontSize: 12,
    fontWeight: '600',
  },
  readyStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  readyStat: {
    overflow: 'hidden',
    color: '#A8F0D4',
    backgroundColor: 'rgba(16,201,124,0.16)',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    fontSize: 12,
    fontWeight: '700',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    width: 100,
    height: 52,
    borderRadius: 26,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: LINE,
  },
  secondaryButtonText: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  buttonDisabled: {
    opacity: 0.4,
  },
  runHero: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    marginBottom: 12,
  },
  guidancePanel: {
    flexGrow: 1,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
    backgroundColor: SCREEN,
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    paddingTop: 6,
    paddingBottom: 24,
    marginTop: 0,
    marginBottom: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -10},
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 10,
    zIndex: 5,
  },
  guidanceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 16,
  },
  guidanceKicker: {
    color: '#5ECBFA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  guidanceTitle: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 4,
    letterSpacing: -0.2,
  },
  guidanceBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: LINE,
  },
  guidanceBadgeText: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '800',
  },
  guidanceInstruction: {
    minHeight: 72,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: SURFACE,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: LINE,
  },
  guidanceInstructionIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidanceInstructionTextBox: {
    flex: 1,
  },
  guidanceInstructionTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '700',
  },
  guidanceInstructionSub: {
    color: TEXT_MUTED,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 4,
  },
  guidanceStats: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  guidanceStat: {
    flex: 1,
    minHeight: 62,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    padding: 12,
    justifyContent: 'center',
  },
  guidanceStatLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 5,
    letterSpacing: 0.3,
  },
  guidanceStatValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '800',
  },
  guidanceVoice: {
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  guidanceVoiceIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidanceVoiceText: {
    flex: 1,
    color: TEXT,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  finishPanel: {
    flexGrow: 1,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
    backgroundColor: SCREEN,
    borderWidth: 1,
    borderColor: LINE,
    padding: 22,
    paddingTop: 6,
    paddingBottom: 24,
    marginTop: 0,
    marginBottom: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -10},
    shadowOpacity: 0.22,
    shadowRadius: 24,
    elevation: 10,
    zIndex: 5,
  },
  finishIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: RUN_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: RUN_GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 6,
  },
  finishKicker: {
    color: '#5ECBFA',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  finishTitle: {
    color: TEXT,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '800',
    marginTop: 6,
    letterSpacing: -0.3,
  },
  finishSub: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    marginTop: 7,
  },
  finishStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
    marginBottom: 18,
  },
  finishStat: {
    flex: 1,
    minHeight: 66,
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    justifyContent: 'center',
  },
  finishStatLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 5,
    letterSpacing: 0.3,
  },
  finishStatValue: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '800',
  },
  shareCardSection: {
    borderRadius: 18,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    marginBottom: 16,
  },
  shareCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  shareCardKicker: {
    color: '#5ECBFA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  shareCardTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '800',
    marginTop: 3,
  },
  sharePreviewCard: {
    minHeight: 300,
    borderRadius: 18,
    backgroundColor: '#0A1423',
    borderWidth: 1,
    borderColor: 'rgba(94,203,250,0.22)',
    padding: 16,
    overflow: 'hidden',
  },
  sharePreviewTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sharePreviewBrand: {
    color: '#5ECBFA',
    fontSize: 12,
    fontWeight: '800',
  },
  sharePreviewName: {
    color: TEXT,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '900',
    marginTop: 4,
  },
  sharePreviewBadge: {
    height: 30,
    borderRadius: 15,
    backgroundColor: RUN_GREEN,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sharePreviewBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  shareRoutePreview: {
    height: 132,
    borderRadius: 16,
    backgroundColor: '#102033',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    marginBottom: 14,
    overflow: 'hidden',
  },
  shareRouteMapImage: {
    width: '100%',
    height: '100%',
  },
  shareRouteMapFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    padding: 16,
  },
  shareRouteMapFallbackText: {
    color: '#A8BFDB',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  shareMetricRow: {
    flexDirection: 'row',
    gap: 8,
  },
  shareMetric: {
    flex: 1,
    minHeight: 66,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    padding: 10,
    justifyContent: 'center',
  },
  shareMetricLabel: {
    color: '#8AA0BC',
    fontSize: 9,
    fontWeight: '800',
    marginBottom: 5,
    letterSpacing: 0.5,
  },
  shareMetricValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  sharePreviewFooter: {
    color: '#A8BFDB',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 12,
  },
  shareSaveButton: {
    height: 48,
    borderRadius: 24,
    backgroundColor: GREEN,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.32,
    shadowRadius: 14,
    elevation: 5,
  },
  shareSaveButtonDone: {
    backgroundColor: RUN_GREEN,
    shadowColor: RUN_GREEN,
  },
  shareSaveButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  finishActions: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryButtonFlex: {
    flex: 1,
    height: 52,
    borderRadius: 26,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: LINE,
  },
  runState: {
    color: '#6EE7B7',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  runDistance: {
    color: TEXT,
    fontSize: 44,
    fontWeight: '900',
    marginTop: 8,
    letterSpacing: -1,
  },
  runTarget: {
    color: TEXT_MUTED,
    fontSize: 13,
    fontWeight: '600',
    marginTop: 2,
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: SURFACE_2,
    overflow: 'hidden',
    marginTop: 18,
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: RUN_GREEN,
  },
  gridThree: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  liveCard: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
  },
  liveLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  liveValue: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 5,
  },
  voiceCard: {
    borderRadius: 14,
    backgroundColor: 'rgba(75,132,243,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(75,132,243,0.25)',
    padding: 14,
    marginBottom: 12,
  },
  voiceLabel: {
    color: '#5ECBFA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  voiceText: {
    color: TEXT,
    marginTop: 7,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 21,
  },
  musicCard: {
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  musicTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  musicSub: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '600',
    marginTop: 3,
  },
  musicBpm: {
    color: '#5ECBFA',
    fontSize: 16,
    fontWeight: '800',
  },
  communitySearchCard: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 4,
  },
  communitySearchBox: {
    height: 46,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  communitySearchInput: {
    flex: 1,
    color: TEXT,
    fontSize: 14,
    fontWeight: '600',
    padding: 0,
  },
  communityFilterRow: {
    gap: 8,
    paddingTop: 10,
    paddingRight: 4,
  },
  communityFilterChip: {
    height: 34,
    minWidth: 64,
    borderRadius: 17,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityFilterChipActive: {
    backgroundColor: GREEN,
    borderColor: GREEN,
  },
  communityFilterText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
  },
  communityFilterTextActive: {
    color: '#fff',
  },
  communityRouteCard: {
    borderRadius: 18,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 5,
  },
  communityRouteImageBox: {
    height: 152,
    borderRadius: 12,
    backgroundColor: '#111827',
    overflow: 'hidden',
    marginBottom: 12,
  },
  communityImageTopRow: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  communityLocationPill: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(14,25,40,0.82)',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
  },
  communityLocationPillText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  communityStartBadge: {
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(14,25,40,0.82)',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  communityStartBadgeOk: {
    backgroundColor: 'rgba(16,201,124,0.22)',
  },
  communityStartBadgeText: {
    color: '#A8C6FC',
    fontSize: 10,
    fontWeight: '700',
  },
  communityStartBadgeTextOk: {
    color: '#6EE7B7',
  },
  communityRouteBody: {
    gap: 10,
  },
  communityRouteTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  communityRouteTitleBox: {
    flex: 1,
  },
  communityRouteTitle: {
    color: TEXT,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  communityRouteMeta: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  communityAuthorBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityAuthorInitial: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  communityAuthorText: {
    color: '#A8C6FC',
    fontSize: 12,
    fontWeight: '600',
  },
  communityDetailBox: {
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
  },
  communityDetailText: {
    color: TEXT,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '600',
  },
  communityTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 10,
  },
  communityTag: {
    height: 28,
    borderRadius: 14,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityTagText: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
  },
  communityDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  communityBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityDetailHeaderText: {
    flex: 1,
  },
  communityDetailKicker: {
    color: '#5ECBFA',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  communityDetailTitle: {
    color: TEXT,
    fontSize: 22,
    fontWeight: '800',
    marginTop: 3,
    letterSpacing: -0.3,
  },
  communityDetailMapCard: {
    height: 260,
    borderRadius: 16,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: LINE,
    overflow: 'hidden',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 6,
  },
  communityDetailMapTop: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  communityDetailMapBottom: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(14,25,40,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
    padding: 14,
  },
  communityDetailMapTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '700',
  },
  communityDetailMapSub: {
    color: '#A8C6FC',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 4,
  },
  communityDetailSummary: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  communityDetailMetric: {
    flex: 1,
    minHeight: 72,
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    justifyContent: 'center',
  },
  communityDetailMetricLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  communityDetailMetricValue: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '800',
  },
  communityDetailSection: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 16,
    gap: 10,
    marginBottom: 12,
  },
  communityDetailSectionTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '800',
  },
  communityDetailActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  communityDetailIconAction: {
    width: 68,
    height: 46,
    borderRadius: 14,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  communityDetailIconActionText: {
    color: TEXT_MUTED,
    fontSize: 9,
    fontWeight: '700',
  },
  communityDetailRunAction: {
    flex: 1,
    height: 46,
    borderRadius: 23,
    backgroundColor: GREEN,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 5,
  },
  communityActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  communityIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityRunButton: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    backgroundColor: GREEN,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  communityRunButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  communityEmptyBox: {
    minHeight: 120,
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  communityEmptyTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '700',
  },
  communityEmptyText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  authContent: {
    flexGrow: 1,
    paddingHorizontal: 26,
    paddingVertical: 36,
    justifyContent: 'center',
  },
  authBrandBlock: {
    alignItems: 'center',
    marginBottom: 28,
  },
  authIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 8,
  },
  authBrand: {
    color: TEXT,
    fontSize: 32,
    fontWeight: '900',
    marginBottom: 12,
    letterSpacing: -0.5,
  },
  authTitle: {
    color: TEXT,
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  authSub: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
    maxWidth: 260,
  },
  authForm: {
    width: '100%',
    maxWidth: 360,
    alignSelf: 'center',
    gap: 10,
  },
  authField: {
    height: 52,
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  authInput: {
    flex: 1,
    color: TEXT,
    fontSize: 14,
    fontWeight: '600',
    padding: 0,
  },
  authPrimaryButton: {
    height: 52,
    borderRadius: 26,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.38,
    shadowRadius: 16,
    elevation: 6,
  },
  authPrimaryButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  authDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 4,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: LINE,
  },
  authDividerText: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '700',
  },
  kakaoButton: {
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FEE500',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  kakaoIconText: {
    color: '#181600',
    fontSize: 16,
    fontWeight: '800',
  },
  kakaoButtonText: {
    color: '#181600',
    fontSize: 14,
    fontWeight: '700',
  },
  googleButton: {
    height: 52,
    borderRadius: 26,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  googleIconText: {
    color: '#3B72F0',
    fontSize: 16,
    fontWeight: '800',
  },
  googleButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  authSwitchButton: {
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authSwitchText: {
    color: '#5ECBFA',
    fontSize: 13,
    fontWeight: '700',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 14,
    minHeight: 130,
    borderRadius: 20,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.24,
    shadowRadius: 24,
    elevation: 8,
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  avatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  profileName: {
    color: TEXT,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  profileHeaderCopy: {
    flex: 1,
  },
  profileSub: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  profileAccountCard: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 16,
    marginBottom: 12,
    gap: 12,
  },
  profileSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  profileSectionTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '800',
  },
  profileStatusPill: {
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(16,201,124,0.14)',
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileStatusText: {
    color: '#6EE7B7',
    fontSize: 10,
    fontWeight: '700',
  },
  profileInfoRow: {
    minHeight: 50,
    borderRadius: 12,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileInfoCopy: {
    flex: 1,
  },
  profileInfoLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  profileInfoValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 3,
  },
  profileReportGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  profileReportItem: {
    flex: 1,
    minHeight: 104,
    borderRadius: 14,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    justifyContent: 'center',
    gap: 6,
  },
  profileReportValue: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '800',
  },
  profileReportLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '600',
  },
  profileDangerCard: {
    borderRadius: 16,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    gap: 10,
    marginTop: 4,
  },
  profileLogoutButton: {
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(75,132,243,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(75,132,243,0.25)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  profileLogoutText: {
    color: '#A8C6FC',
    fontSize: 13,
    fontWeight: '700',
  },
  profileDeleteButton: {
    height: 46,
    borderRadius: 23,
    backgroundColor: 'rgba(239,68,68,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.22)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  profileDeleteText: {
    color: '#FCA5A5',
    fontSize: 13,
    fontWeight: '700',
  },
  profileRunRecordCard: {
    minHeight: 72,
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 4,
  },
  profileRunSharePill: {
    height: 30,
    minWidth: 52,
    borderRadius: 15,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  profileRunSharePillActive: {
    backgroundColor: 'rgba(16,201,124,0.14)',
    borderColor: 'rgba(16,201,124,0.35)',
  },
  profileRunShareText: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
  },
  profileRunShareTextActive: {
    color: '#6EE7B7',
  },
  profileRunDetailHero: {
    borderRadius: 18,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 22,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 6,
  },
  profileRunDetailBadge: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: GREEN,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.38,
    shadowRadius: 16,
    elevation: 5,
  },
  profileRunDetailTitle: {
    color: TEXT,
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  profileRunDetailSub: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
    marginTop: 7,
  },
  listTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 10,
  },
  runCard: {
    minHeight: 70,
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  runBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(75,132,243,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(75,132,243,0.3)',
  },
  runBadgeText: {
    color: '#7DAEFC',
    fontSize: 18,
    fontWeight: '800',
  },
  runCardBody: {
    flex: 1,
  },
  runCardTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '700',
  },
  runCardSub: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 3,
  },
  smallButton: {
    minWidth: 58,
    height: 32,
    borderRadius: 16,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: LINE,
  },
  smallButtonText: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '700',
  },
  footer: {
    minHeight: 66,
    paddingTop: 8,
    paddingHorizontal: 10,
    backgroundColor: SURFACE,
    borderTopWidth: 1,
    borderTopColor: LINE,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -6},
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
    zIndex: 20,
  },
  footerItem: {
    flex: 1,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    borderRadius: 14,
    marginHorizontal: 3,
  },
  footerItemActive: {
    backgroundColor: 'rgba(75,132,243,0.12)',
  },
  footerLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '700',
  },
  footerActive: {
    color: GREEN,
  },
});
