import {Platform, StyleSheet} from 'react-native';
import {GREEN, LINE, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from './theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  header: {
    height: 64,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: SCREEN,
  },
  brand: {
    fontSize: 25,
    fontWeight: '900',
    color: TEXT,
  },
  brandSub: {
    fontSize: 11,
    fontWeight: '700',
    color: TEXT_MUTED,
    marginTop: 1,
  },
  headerPill: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerPillText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  mapShell: {
    height: Platform.OS === 'ios' ? 255 : 245,
    marginHorizontal: 14,
    marginBottom: 12,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.25,
    shadowRadius: 22,
    elevation: 8,
  },
  navigationMapShell: {
    height: Platform.OS === 'ios' ? 470 : 450,
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 0,
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
    zIndex: 0,
  },
  webview: {
    flex: 1,
    backgroundColor: '#e5e7eb',
  },
  mapOverlay: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 8,
    backgroundColor: 'rgba(29,38,56,0.94)',
  },
  mapTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  mapSub: {
    marginTop: 2,
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '700',
  },
  navigationBanner: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 16,
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 7,
  },
  navigationBannerIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationBannerTextBox: {
    flex: 1,
  },
  navigationBannerTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  navigationBannerSub: {
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 2,
  },
  navigationPacePill: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(17,24,39,0.86)',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navigationPaceText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(21,28,43,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingCard: {
    minWidth: 146,
    alignItems: 'center',
    gap: 10,
    padding: 18,
    borderRadius: 8,
    backgroundColor: SURFACE,
  },
  loadingText: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '800',
  },
  contentShell: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  navigationContentShell: {
    backgroundColor: 'transparent',
    marginTop: -58,
    zIndex: 3,
    elevation: 3,
  },
  navigationContentShellExpanded: {
    marginTop: -260,
  },
  homeScroll: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  homeContent: {
    padding: 18,
    paddingBottom: 30,
  },
  homeHero: {
    minHeight: 346,
    borderRadius: 8,
    backgroundColor: '#1d2638',
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 14},
    shadowOpacity: 0.28,
    shadowRadius: 24,
    elevation: 8,
  },
  heroShadePanel: {
    position: 'absolute',
    left: -60,
    bottom: -48,
    width: 248,
    height: 122,
    borderRadius: 8,
    backgroundColor: 'rgba(15,23,42,0.58)',
    transform: [{rotate: '-12deg'}],
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroKicker: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
  },
  heroTitle: {
    width: 224,
    color: '#f8fafc',
    fontSize: 30,
    lineHeight: 37,
    fontWeight: '900',
    marginTop: 8,
  },
  heroReason: {
    width: 238,
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 8,
  },
  heroRouteCard: {
    minHeight: 126,
    borderRadius: 8,
    backgroundColor: 'rgba(15,23,42,0.78)',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 12,
    marginTop: 18,
    flexDirection: 'row',
    gap: 12,
  },
  heroMapPreview: {
    width: 92,
    borderRadius: 8,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  previewImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  previewScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.22)',
  },
  previewBadge: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    minWidth: 42,
    height: 24,
    borderRadius: 6,
    backgroundColor: 'rgba(47,128,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  previewBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
  },
  heroRouteInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  heroStatRow: {
    flexDirection: 'row',
    gap: 6,
  },
  heroStatPill: {
    flex: 1,
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: '#243452',
    paddingHorizontal: 8,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  heroStatLabel: {
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: '900',
    marginBottom: 4,
  },
  heroStatValue: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '900',
  },
  heroRouteHint: {
    color: '#bfdbfe',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 10,
  },
  routePreviewStack: {
    height: 122,
    marginTop: 16,
  },
  routePreviewBack: {
    position: 'absolute',
    right: 14,
    top: 28,
    width: 210,
    height: 82,
    borderRadius: 8,
    backgroundColor: '#111827',
    opacity: 0.75,
    transform: [{rotate: '-8deg'}],
  },
  routePreviewMid: {
    position: 'absolute',
    right: 34,
    top: 12,
    width: 214,
    height: 88,
    borderRadius: 8,
    backgroundColor: '#26364f',
    transform: [{rotate: '-8deg'}],
  },
  routePreviewFront: {
    position: 'absolute',
    right: 54,
    top: 0,
    width: 220,
    height: 96,
    borderRadius: 8,
    backgroundColor: '#dbeafe',
    padding: 14,
    transform: [{rotate: '-8deg'}],
  },
  routePreviewShape: {
    position: 'absolute',
    right: 18,
    top: 16,
    color: '#2563eb',
    fontSize: 38,
    fontWeight: '900',
  },
  routeLineOne: {
    width: 102,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#60a5fa',
    marginTop: 12,
  },
  routeLineTwo: {
    width: 72,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#93c5fd',
    marginTop: 10,
  },
  routeLineThree: {
    width: 126,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#bfdbfe',
    marginTop: 10,
  },
  heroBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    gap: 12,
  },
  heroRouteName: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '900',
  },
  heroRouteMeta: {
    color: '#94a3b8',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  heroButton: {
    minWidth: 92,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  quickCreateCard: {
    borderRadius: 8,
    backgroundColor: '#202b40',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 14,
    marginBottom: 18,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  quickCreateHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  quickCreateKicker: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  quickCreateTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 4,
  },
  quickCreateIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickPromptBox: {
    height: 46,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    justifyContent: 'center',
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  quickPromptInput: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '800',
    padding: 0,
  },
  quickWheelContent: {
    gap: 8,
    paddingRight: 4,
    marginBottom: 10,
  },
  quickWheelItem: {
    height: 38,
    minWidth: 74,
    borderRadius: 8,
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  quickWheelItemActive: {
    backgroundColor: '#2f80ff',
    borderColor: '#60a5fa',
  },
  quickWheelText: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '900',
  },
  quickWheelTextActive: {
    color: '#fff',
  },
  quickDistanceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quickDistance: {
    width: 58,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickDistanceActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#dbeafe',
  },
  quickDistanceText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '900',
  },
  quickDistanceTextActive: {
    color: '#1d4ed8',
  },
  quickGenerateButton: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#60a5fa',
  },
  quickGenerateText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  sectionHeaderInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  homeSectionTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '900',
  },
  homeSectionLink: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
  },
  popularRouteScroller: {
    gap: 12,
    paddingRight: 18,
    paddingBottom: 2,
  },
  popularRouteCard: {
    width: 278,
    minHeight: 214,
    borderRadius: 8,
    backgroundColor: '#202b40',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 12,
    marginBottom: 10,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 5,
  },
  popularMapPreview: {
    height: 104,
    borderRadius: 8,
    backgroundColor: '#111827',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  popularImageLabel: {
    position: 'absolute',
    left: 10,
    top: 10,
    height: 26,
    borderRadius: 6,
    backgroundColor: 'rgba(17,24,39,0.76)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  popularImageLabelText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  popularRouteBody: {
    flex: 1,
  },
  popularTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
  },
  popularLocation: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 5,
  },
  popularSub: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 5,
  },
  popularUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 12,
  },
  popularAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  popularAvatarText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
  },
  popularUser: {
    color: '#bfdbfe',
    fontSize: 11,
    fontWeight: '800',
  },
  panelScroll: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  navigationPanelScroll: {
    backgroundColor: 'transparent',
  },
  panelContent: {
    padding: 18,
    paddingBottom: 18,
  },
  navigationPanelContent: {
    flexGrow: 1,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
  },
  runBottomSheet: {
    flexGrow: 1,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    overflow: 'hidden',
    backgroundColor: SCREEN,
    borderTopWidth: 1,
    borderColor: LINE,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 24,
    marginTop: 0,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 5,
  },
  sheetDragHandleArea: {
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  sheetDragHandle: {
    width: 48,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#334155',
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  sheetHeaderButton: {
    height: 34,
    minWidth: 52,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  sheetHeaderButtonText: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '900',
  },
  runSetupCard: {
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    marginBottom: 16,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  runSetupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  runSetupKicker: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  runSetupTitle: {
    color: TEXT,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
    marginTop: 4,
  },
  runSetupBadge: {
    minWidth: 76,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  runSetupBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  runSetupGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  runSetupMetric: {
    flex: 1,
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: '#243452',
    padding: 10,
    justifyContent: 'center',
  },
  runSetupMetricLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 5,
  },
  runSetupMetricValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: TEXT,
  },
  sectionMeta: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: TEXT_MUTED,
  },
  inputBlock: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: TEXT_MUTED,
    marginBottom: 7,
  },
  textInput: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    paddingHorizontal: 14,
    color: TEXT,
    fontSize: 15,
    fontWeight: '700',
  },
  chipRow: {
    gap: 8,
    paddingRight: 8,
    marginBottom: 14,
  },
  shapeChip: {
    minWidth: 132,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  shapeChipActive: {
    borderColor: '#38bdf8',
    backgroundColor: '#233a5d',
  },
  shapeIconBox: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shapeIconBoxActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#dbeafe',
  },
  shapeChipCopy: {
    flex: 1,
  },
  shapeChipText: {
    fontSize: 14,
    fontWeight: '900',
    color: TEXT,
  },
  shapeChipHint: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '700',
    color: TEXT_MUTED,
  },
  shapeChipTextActive: {
    color: '#bfdbfe',
  },
  gridTwo: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  metricCard: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    padding: 13,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 4,
  },
  metricLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '800',
  },
  metricValue: {
    marginTop: 4,
    color: TEXT,
    fontSize: 22,
    fontWeight: '900',
  },
  slider: {
    width: '100%',
    height: 34,
    marginBottom: 4,
  },
  segmented: {
    flexDirection: 'row',
    backgroundColor: '#111827',
    borderRadius: 8,
    padding: 3,
    marginTop: 4,
    marginBottom: 12,
  },
  segment: {
    flex: 1,
    height: 36,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: '#2f80ff',
  },
  segmentText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#fff',
  },
  optionList: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    marginBottom: 12,
  },
  toggleRow: {
    minHeight: 48,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: LINE,
  },
  toggleLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: TEXT,
  },
  locationButton: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: '#1d3f68',
    borderWidth: 1,
    borderColor: '#2f80ff',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  locationIconBox: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#102742',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationTextBox: {
    flex: 1,
  },
  locationTitle: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '900',
  },
  locationSub: {
    marginTop: 2,
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  readyCard: {
    borderRadius: 8,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: LINE,
    padding: 15,
    marginBottom: 12,
  },
  readyTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  readySub: {
    color: '#cbd5e1',
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
  },
  readyStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 13,
  },
  readyStat: {
    overflow: 'hidden',
    color: '#d1fae5',
    backgroundColor: 'rgba(16,185,129,0.18)',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 6,
    fontSize: 12,
    fontWeight: '900',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 8,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#60a5fa',
    shadowColor: '#2563eb',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.36,
    shadowRadius: 18,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    width: 100,
    height: 52,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: LINE,
  },
  secondaryButtonText: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  runHero: {
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    marginBottom: 12,
  },
  guidancePanel: {
    flexGrow: 1,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    backgroundColor: SCREEN,
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    paddingTop: 8,
    paddingBottom: 24,
    marginTop: 0,
    marginBottom: 0,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 5,
  },
  guidanceHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
  },
  guidanceKicker: {
    color: '#2f80ff',
    fontSize: 11,
    fontWeight: '900',
  },
  guidanceTitle: {
    color: TEXT,
    fontSize: 19,
    fontWeight: '900',
    marginTop: 4,
  },
  guidanceBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidanceBadgeText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  guidanceInstruction: {
    minHeight: 72,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: SURFACE,
    padding: 12,
    marginBottom: 12,
  },
  guidanceInstructionIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidanceInstructionTextBox: {
    flex: 1,
  },
  guidanceInstructionTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '900',
  },
  guidanceInstructionSub: {
    color: TEXT_MUTED,
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  guidanceStats: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  guidanceStat: {
    flex: 1,
    minHeight: 62,
    borderRadius: 8,
    backgroundColor: '#111827',
    padding: 10,
    justifyContent: 'center',
  },
  guidanceStatLabel: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 5,
  },
  guidanceStatValue: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '900',
  },
  guidanceVoice: {
    borderRadius: 8,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: SURFACE_2,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  guidanceVoiceIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  guidanceVoiceText: {
    flex: 1,
    color: TEXT,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  finishPanel: {
    flexGrow: 1,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    backgroundColor: SCREEN,
    borderWidth: 1,
    borderColor: LINE,
    padding: 20,
    paddingTop: 8,
    paddingBottom: 24,
    marginTop: 0,
    marginBottom: 0,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 5,
  },
  finishIcon: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  finishKicker: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
  },
  finishTitle: {
    color: TEXT,
    fontSize: 24,
    lineHeight: 31,
    fontWeight: '900',
    marginTop: 6,
  },
  finishSub: {
    color: TEXT_MUTED,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
    marginTop: 7,
  },
  finishStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    marginBottom: 16,
  },
  finishStat: {
    flex: 1,
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: '#111827',
    padding: 10,
    justifyContent: 'center',
  },
  finishStatLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 5,
  },
  finishStatValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  finishActions: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryButtonFlex: {
    flex: 1,
    height: 52,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: LINE,
  },
  runState: {
    color: '#86efac',
    fontSize: 11,
    fontWeight: '900',
  },
  runDistance: {
    color: '#fff',
    fontSize: 42,
    fontWeight: '900',
    marginTop: 8,
  },
  runTarget: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  progressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: '#111827',
    overflow: 'hidden',
    marginTop: 16,
  },
  progressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: GREEN,
  },
  gridThree: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  liveCard: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 11,
  },
  liveLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
  },
  liveValue: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 5,
  },
  voiceCard: {
    borderRadius: 8,
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#345a86',
    padding: 14,
    marginBottom: 12,
  },
  voiceLabel: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  voiceText: {
    color: TEXT,
    marginTop: 6,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 21,
  },
  musicCard: {
    borderRadius: 8,
    backgroundColor: '#1d3f68',
    borderWidth: 1,
    borderColor: '#2f80ff',
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  musicTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '900',
  },
  musicSub: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  musicBpm: {
    color: '#38bdf8',
    fontSize: 16,
    fontWeight: '900',
  },
  communitySearchCard: {
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 16,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 5,
  },
  communitySearchBox: {
    height: 48,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  communitySearchInput: {
    flex: 1,
    color: TEXT,
    fontSize: 14,
    fontWeight: '800',
    padding: 0,
  },
  communityFilterRow: {
    gap: 8,
    paddingTop: 10,
    paddingRight: 4,
  },
  communityFilterChip: {
    height: 36,
    minWidth: 68,
    borderRadius: 8,
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#334155',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityFilterChipActive: {
    backgroundColor: '#2f80ff',
    borderColor: '#60a5fa',
  },
  communityFilterText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '900',
  },
  communityFilterTextActive: {
    color: '#fff',
  },
  communityRouteCard: {
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 14,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 5,
  },
  communityRouteImageBox: {
    height: 150,
    borderRadius: 8,
    backgroundColor: '#111827',
    overflow: 'hidden',
    marginBottom: 12,
  },
  communityImageTopRow: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  communityLocationPill: {
    minHeight: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(17,24,39,0.78)',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 1,
  },
  communityLocationPillText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  communityStartBadge: {
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(29,63,104,0.86)',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  communityStartBadgeOk: {
    backgroundColor: 'rgba(22,101,52,0.86)',
  },
  communityStartBadgeText: {
    color: '#bfdbfe',
    fontSize: 10,
    fontWeight: '900',
  },
  communityStartBadgeTextOk: {
    color: '#bbf7d0',
  },
  communityRouteBody: {
    gap: 10,
  },
  communityRouteTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  communityRouteTitleBox: {
    flex: 1,
  },
  communityRouteTitle: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '900',
  },
  communityRouteMeta: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  communityAuthorBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityAuthorInitial: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  communityAuthorText: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '800',
  },
  communityDetailBox: {
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 12,
  },
  communityDetailText: {
    color: TEXT,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '800',
  },
  communityTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 10,
  },
  communityTag: {
    height: 28,
    borderRadius: 6,
    backgroundColor: '#243452',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityTagText: {
    color: '#bfdbfe',
    fontSize: 10,
    fontWeight: '900',
  },
  communityDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  communityBackButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityDetailHeaderText: {
    flex: 1,
  },
  communityDetailKicker: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  communityDetailTitle: {
    color: TEXT,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 3,
  },
  communityDetailMapCard: {
    height: 260,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: LINE,
    overflow: 'hidden',
    marginBottom: 12,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 6,
  },
  communityDetailMapTop: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  communityDetailMapBottom: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 14,
    borderRadius: 8,
    backgroundColor: 'rgba(17,24,39,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.24)',
    padding: 12,
  },
  communityDetailMapTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '900',
  },
  communityDetailMapSub: {
    color: '#bfdbfe',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  communityDetailSummary: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  communityDetailMetric: {
    flex: 1,
    minHeight: 72,
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 11,
    justifyContent: 'center',
  },
  communityDetailMetricLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 6,
  },
  communityDetailMetricValue: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '900',
  },
  communityDetailSection: {
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    gap: 10,
    marginBottom: 12,
  },
  communityDetailSectionTitle: {
    color: TEXT,
    fontSize: 17,
    fontWeight: '900',
  },
  communityDetailActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  communityDetailIconAction: {
    width: 70,
    height: 46,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  communityDetailIconActionText: {
    color: TEXT_MUTED,
    fontSize: 9,
    fontWeight: '900',
  },
  communityDetailRunAction: {
    flex: 1,
    height: 46,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    borderWidth: 1,
    borderColor: '#60a5fa',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  communityActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  communityIconButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  communityRunButton: {
    flex: 1,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    borderWidth: 1,
    borderColor: '#60a5fa',
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  communityRunButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  communityEmptyBox: {
    minHeight: 118,
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  communityEmptyTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '900',
  },
  communityEmptyText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 6,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
    minHeight: 132,
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    overflow: 'hidden',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 14},
    shadowOpacity: 0.22,
    shadowRadius: 22,
    elevation: 8,
  },
  profileBlade: {
    position: 'absolute',
    right: -36,
    top: -52,
    width: 142,
    height: 220,
    borderRadius: 42,
    backgroundColor: '#2f80ff',
    transform: [{rotate: '24deg'}],
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  profileName: {
    color: TEXT,
    fontSize: 20,
    fontWeight: '900',
  },
  profileSub: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  listTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 10,
  },
  runCard: {
    minHeight: 70,
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  runBadge: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#1d3f68',
    alignItems: 'center',
    justifyContent: 'center',
  },
  runBadgeText: {
    color: '#38bdf8',
    fontSize: 18,
    fontWeight: '900',
  },
  runCardBody: {
    flex: 1,
  },
  runCardTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  runCardSub: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  smallButton: {
    minWidth: 58,
    height: 34,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  smallButtonText: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '900',
  },
  footer: {
    minHeight: 70,
    paddingTop: 9,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(17,24,39,0.96)',
    borderTopWidth: 1,
    borderTopColor: LINE,
    flexDirection: 'row',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 10,
    zIndex: 20,
  },
  footerItem: {
    flex: 1,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    borderRadius: 8,
    marginHorizontal: 3,
  },
  footerItemActive: {
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#2f80ff',
    shadowColor: '#2563eb',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
  },
  footerLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '900',
  },
  footerActive: {
    color: '#38bdf8',
  },
});
