import {Platform, StyleSheet} from 'react-native';
import {GREEN, LINE, SCREEN, SURFACE, SURFACE_2, TEXT, TEXT_MUTED} from './theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  header: {
    height: 64,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: SCREEN,
  },
  brand: {
    fontSize: 25,
    fontWeight: '900',
    color: TEXT,
  },
  brandSub: {
    fontSize: 11,
    fontWeight: '700',
    color: TEXT_MUTED,
    marginTop: 1,
  },
  headerPill: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerPillText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
  },
  mapShell: {
    height: Platform.OS === 'ios' ? 255 : 245,
    marginHorizontal: 14,
    marginBottom: 12,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.25,
    shadowRadius: 22,
    elevation: 8,
  },
  webview: {
    flex: 1,
    backgroundColor: '#e5e7eb',
  },
  mapOverlay: {
    position: 'absolute',
    left: 14,
    right: 14,
    top: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 8,
    backgroundColor: 'rgba(29,38,56,0.94)',
  },
  mapTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  mapSub: {
    marginTop: 2,
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '700',
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(21,28,43,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingCard: {
    minWidth: 146,
    alignItems: 'center',
    gap: 10,
    padding: 18,
    borderRadius: 8,
    backgroundColor: SURFACE,
  },
  loadingText: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '800',
  },
  contentShell: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  homeScroll: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  homeContent: {
    padding: 18,
    paddingBottom: 30,
  },
  homeHero: {
    minHeight: 346,
    borderRadius: 8,
    backgroundColor: '#1d2638',
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 14},
    shadowOpacity: 0.28,
    shadowRadius: 24,
    elevation: 8,
  },
  heroBlueBlade: {
    position: 'absolute',
    right: -78,
    top: -54,
    width: 190,
    height: 430,
    borderRadius: 56,
    backgroundColor: '#2f80ff',
    transform: [{rotate: '22deg'}],
  },
  heroShadePanel: {
    position: 'absolute',
    left: -60,
    bottom: -48,
    width: 248,
    height: 122,
    borderRadius: 8,
    backgroundColor: 'rgba(15,23,42,0.58)',
    transform: [{rotate: '-12deg'}],
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  heroKicker: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
  },
  heroTitle: {
    width: 224,
    color: '#f8fafc',
    fontSize: 30,
    lineHeight: 37,
    fontWeight: '900',
    marginTop: 8,
  },
  heroReason: {
    width: 238,
    color: '#94a3b8',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '800',
    marginTop: 8,
  },
  heroScore: {
    width: 58,
    height: 58,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroScoreValue: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  heroScoreLabel: {
    color: '#dbeafe',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 1,
  },
  heroRouteCard: {
    minHeight: 126,
    borderRadius: 8,
    backgroundColor: 'rgba(15,23,42,0.78)',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 12,
    marginTop: 18,
    flexDirection: 'row',
    gap: 12,
  },
  heroMapPreview: {
    width: 92,
    borderRadius: 8,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  previewImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  previewScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.22)',
  },
  previewBadge: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    minWidth: 42,
    height: 24,
    borderRadius: 6,
    backgroundColor: 'rgba(47,128,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  previewBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
  },
  heroRouteInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  heroStatRow: {
    flexDirection: 'row',
    gap: 6,
  },
  heroStatPill: {
    flex: 1,
    minHeight: 58,
    borderRadius: 8,
    backgroundColor: '#243452',
    paddingHorizontal: 8,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  heroStatLabel: {
    color: '#94a3b8',
    fontSize: 9,
    fontWeight: '900',
    marginBottom: 4,
  },
  heroStatValue: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '900',
  },
  heroRouteHint: {
    color: '#bfdbfe',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 10,
  },
  routePreviewStack: {
    height: 122,
    marginTop: 16,
  },
  routePreviewBack: {
    position: 'absolute',
    right: 14,
    top: 28,
    width: 210,
    height: 82,
    borderRadius: 8,
    backgroundColor: '#111827',
    opacity: 0.75,
    transform: [{rotate: '-8deg'}],
  },
  routePreviewMid: {
    position: 'absolute',
    right: 34,
    top: 12,
    width: 214,
    height: 88,
    borderRadius: 8,
    backgroundColor: '#26364f',
    transform: [{rotate: '-8deg'}],
  },
  routePreviewFront: {
    position: 'absolute',
    right: 54,
    top: 0,
    width: 220,
    height: 96,
    borderRadius: 8,
    backgroundColor: '#dbeafe',
    padding: 14,
    transform: [{rotate: '-8deg'}],
  },
  routePreviewShape: {
    position: 'absolute',
    right: 18,
    top: 16,
    color: '#2563eb',
    fontSize: 38,
    fontWeight: '900',
  },
  routeLineOne: {
    width: 102,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#60a5fa',
    marginTop: 12,
  },
  routeLineTwo: {
    width: 72,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#93c5fd',
    marginTop: 10,
  },
  routeLineThree: {
    width: 126,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#bfdbfe',
    marginTop: 10,
  },
  heroBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    gap: 12,
  },
  heroRouteName: {
    color: '#f8fafc',
    fontSize: 14,
    fontWeight: '900',
  },
  heroRouteMeta: {
    color: '#94a3b8',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 4,
  },
  heroButton: {
    minWidth: 92,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  quickCreateCard: {
    borderRadius: 8,
    backgroundColor: '#202b40',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 14,
    marginBottom: 18,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  quickCreateHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  quickCreateKicker: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  quickCreateTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 4,
  },
  quickCreateIcon: {
    color: '#38bdf8',
    fontSize: 26,
    fontWeight: '900',
  },
  quickCreateRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  quickChoice: {
    flex: 1,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickChoiceActive: {
    backgroundColor: '#2f80ff',
    borderColor: '#60a5fa',
  },
  quickChoiceText: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '900',
  },
  quickChoiceTextActive: {
    color: '#fff',
  },
  quickDistanceRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quickDistance: {
    width: 58,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#111827',
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickDistanceActive: {
    backgroundColor: '#dbeafe',
    borderColor: '#dbeafe',
  },
  quickDistanceText: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '900',
  },
  quickDistanceTextActive: {
    color: '#1d4ed8',
  },
  quickGenerateButton: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#60a5fa',
  },
  quickGenerateText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  sectionHeaderInline: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  homeSectionTitle: {
    color: '#f8fafc',
    fontSize: 17,
    fontWeight: '900',
  },
  homeSectionLink: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
  },
  recommendCard: {
    minHeight: 116,
    borderRadius: 8,
    backgroundColor: '#202b40',
    padding: 12,
    marginBottom: 18,
    flexDirection: 'row',
    gap: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  recommendArt: {
    width: 86,
    borderRadius: 8,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  recommendBody: {
    flex: 1,
    justifyContent: 'center',
  },
  recommendTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
  },
  recommendSub: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
    marginTop: 5,
  },
  recommendTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
    alignItems: 'center',
  },
  recommendTag: {
    height: 34,
    minWidth: 64,
    borderRadius: 6,
    backgroundColor: '#293952',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  recommendTagText: {
    color: '#bfdbfe',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  healthGrid: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 18,
  },
  healthCard: {
    flex: 1,
    minHeight: 92,
    borderRadius: 8,
    backgroundColor: '#eaf2ff',
    padding: 11,
  },
  healthLabel: {
    color: '#64748b',
    fontSize: 10,
    fontWeight: '900',
  },
  healthValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 7,
  },
  healthDelta: {
    color: '#2563eb',
    fontSize: 10,
    lineHeight: 14,
    fontWeight: '900',
    marginTop: 7,
  },
  popularRouteScroller: {
    gap: 12,
    paddingRight: 18,
    paddingBottom: 2,
  },
  popularRouteCard: {
    width: 278,
    minHeight: 214,
    borderRadius: 8,
    backgroundColor: '#202b40',
    borderWidth: 1,
    borderColor: '#334155',
    padding: 12,
    marginBottom: 10,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.16,
    shadowRadius: 16,
    elevation: 5,
  },
  popularMapPreview: {
    height: 104,
    borderRadius: 8,
    backgroundColor: '#111827',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  popularImageLabel: {
    position: 'absolute',
    left: 10,
    top: 10,
    height: 26,
    borderRadius: 6,
    backgroundColor: 'rgba(17,24,39,0.76)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  popularImageLabelText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  popularRouteBody: {
    flex: 1,
  },
  popularTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '900',
  },
  popularLocation: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 5,
  },
  popularSub: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 5,
  },
  popularUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 12,
  },
  popularAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  popularAvatarText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
  },
  popularUser: {
    color: '#bfdbfe',
    fontSize: 11,
    fontWeight: '800',
  },
  panelScroll: {
    flex: 1,
    backgroundColor: SCREEN,
  },
  panelContent: {
    padding: 18,
    paddingBottom: 18,
  },
  runSetupCard: {
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 14,
    marginBottom: 16,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  runSetupHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 12,
  },
  runSetupKicker: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  runSetupTitle: {
    color: TEXT,
    fontSize: 19,
    lineHeight: 25,
    fontWeight: '900',
    marginTop: 4,
  },
  runSetupBadge: {
    minWidth: 76,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  runSetupBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  runSetupGrid: {
    flexDirection: 'row',
    gap: 8,
  },
  runSetupMetric: {
    flex: 1,
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: '#243452',
    padding: 10,
    justifyContent: 'center',
  },
  runSetupMetricLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
    marginBottom: 5,
  },
  runSetupMetricValue: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: TEXT,
  },
  sectionMeta: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
    color: TEXT_MUTED,
  },
  inputBlock: {
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: TEXT_MUTED,
    marginBottom: 7,
  },
  textInput: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    paddingHorizontal: 14,
    color: TEXT,
    fontSize: 15,
    fontWeight: '700',
  },
  chipRow: {
    gap: 8,
    paddingRight: 8,
    marginBottom: 14,
  },
  shapeChip: {
    minWidth: 82,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  shapeChipActive: {
    borderColor: '#38bdf8',
    backgroundColor: '#233a5d',
  },
  shapeChipText: {
    fontSize: 14,
    fontWeight: '900',
    color: TEXT,
  },
  shapeChipHint: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '700',
    color: TEXT_MUTED,
  },
  shapeChipTextActive: {
    color: '#bfdbfe',
  },
  gridTwo: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  metricCard: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    padding: 13,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 4,
  },
  metricLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '800',
  },
  metricValue: {
    marginTop: 4,
    color: TEXT,
    fontSize: 22,
    fontWeight: '900',
  },
  slider: {
    width: '100%',
    height: 34,
    marginBottom: 4,
  },
  segmented: {
    flexDirection: 'row',
    backgroundColor: '#111827',
    borderRadius: 8,
    padding: 3,
    marginTop: 4,
    marginBottom: 12,
  },
  segment: {
    flex: 1,
    height: 36,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: {
    backgroundColor: '#2f80ff',
  },
  segmentText: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '900',
  },
  segmentTextActive: {
    color: '#fff',
  },
  optionList: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: LINE,
    backgroundColor: SURFACE,
    marginBottom: 12,
  },
  toggleRow: {
    minHeight: 48,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: LINE,
  },
  toggleLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: TEXT,
  },
  locationButton: {
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: '#1d3f68',
    borderWidth: 1,
    borderColor: '#2f80ff',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  locationIcon: {
    fontSize: 24,
    color: '#38bdf8',
    fontWeight: '900',
  },
  locationTextBox: {
    flex: 1,
  },
  locationTitle: {
    color: TEXT,
    fontSize: 13,
    fontWeight: '900',
  },
  locationSub: {
    marginTop: 2,
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  readyCard: {
    borderRadius: 8,
    backgroundColor: '#0f172a',
    borderWidth: 1,
    borderColor: LINE,
    padding: 15,
    marginBottom: 12,
  },
  readyTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  readySub: {
    color: '#cbd5e1',
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
  },
  readyStats: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 13,
  },
  readyStat: {
    overflow: 'hidden',
    color: '#d1fae5',
    backgroundColor: 'rgba(16,185,129,0.18)',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 6,
    fontSize: 12,
    fontWeight: '900',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 8,
    backgroundColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#60a5fa',
    shadowColor: '#2563eb',
    shadowOffset: {width: 0, height: 10},
    shadowOpacity: 0.36,
    shadowRadius: 18,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  secondaryButton: {
    width: 100,
    height: 52,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: LINE,
  },
  secondaryButtonText: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  runHero: {
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    marginBottom: 12,
  },
  runState: {
    color: '#86efac',
    fontSize: 11,
    fontWeight: '900',
  },
  runDistance: {
    color: '#fff',
    fontSize: 42,
    fontWeight: '900',
    marginTop: 8,
  },
  runTarget: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 2,
  },
  progressTrack: {
    height: 10,
    borderRadius: 5,
    backgroundColor: '#111827',
    overflow: 'hidden',
    marginTop: 16,
  },
  progressFill: {
    height: '100%',
    borderRadius: 5,
    backgroundColor: GREEN,
  },
  gridThree: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  liveCard: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 11,
  },
  liveLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
  },
  liveValue: {
    color: TEXT,
    fontSize: 18,
    fontWeight: '900',
    marginTop: 5,
  },
  voiceCard: {
    borderRadius: 8,
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#345a86',
    padding: 14,
    marginBottom: 12,
  },
  voiceLabel: {
    color: '#38bdf8',
    fontSize: 11,
    fontWeight: '900',
  },
  voiceText: {
    color: TEXT,
    marginTop: 6,
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 21,
  },
  musicCard: {
    borderRadius: 8,
    backgroundColor: '#1d3f68',
    borderWidth: 1,
    borderColor: '#2f80ff',
    padding: 14,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  musicTitle: {
    color: TEXT,
    fontSize: 15,
    fontWeight: '900',
  },
  musicSub: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  musicBpm: {
    color: '#38bdf8',
    fontSize: 16,
    fontWeight: '900',
  },
  communityHero: {
    minHeight: 178,
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    marginBottom: 16,
    overflow: 'hidden',
    justifyContent: 'space-between',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 14},
    shadowOpacity: 0.22,
    shadowRadius: 22,
    elevation: 8,
  },
  communityBlade: {
    position: 'absolute',
    right: -54,
    top: -36,
    width: 174,
    height: 246,
    borderRadius: 48,
    backgroundColor: '#2f80ff',
    transform: [{rotate: '26deg'}],
  },
  communityTitle: {
    width: 214,
    color: TEXT,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '900',
    marginTop: 8,
  },
  communityMeta: {
    width: 210,
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
  },
  communityStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  communityStat: {
    minWidth: 84,
    borderRadius: 8,
    backgroundColor: 'rgba(32,43,64,0.9)',
    borderWidth: 1,
    borderColor: '#46617f',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  communityStatValue: {
    color: '#38bdf8',
    fontSize: 18,
    fontWeight: '900',
  },
  communityStatLabel: {
    color: TEXT_MUTED,
    fontSize: 10,
    fontWeight: '900',
    marginTop: 2,
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
    minHeight: 132,
    borderRadius: 8,
    backgroundColor: '#1d2638',
    borderWidth: 1,
    borderColor: LINE,
    padding: 18,
    overflow: 'hidden',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 14},
    shadowOpacity: 0.22,
    shadowRadius: 22,
    elevation: 8,
  },
  profileBlade: {
    position: 'absolute',
    right: -36,
    top: -52,
    width: 142,
    height: 220,
    borderRadius: 42,
    backgroundColor: '#2f80ff',
    transform: [{rotate: '24deg'}],
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#2f80ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  profileName: {
    color: TEXT,
    fontSize: 20,
    fontWeight: '900',
  },
  profileSub: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  listTitle: {
    color: TEXT,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 10,
  },
  runCard: {
    minHeight: 70,
    borderRadius: 8,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: LINE,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 4,
  },
  runBadge: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#1d3f68',
    alignItems: 'center',
    justifyContent: 'center',
  },
  runBadgeText: {
    color: '#38bdf8',
    fontSize: 18,
    fontWeight: '900',
  },
  runCardBody: {
    flex: 1,
  },
  runCardTitle: {
    color: TEXT,
    fontSize: 14,
    fontWeight: '900',
  },
  runCardSub: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
  },
  smallButton: {
    minWidth: 58,
    height: 34,
    borderRadius: 8,
    backgroundColor: SURFACE_2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  smallButtonText: {
    color: TEXT,
    fontSize: 12,
    fontWeight: '900',
  },
  footer: {
    minHeight: 70,
    paddingTop: 9,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(17,24,39,0.96)',
    borderTopWidth: 1,
    borderTopColor: LINE,
    flexDirection: 'row',
    shadowColor: '#020617',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 10,
  },
  footerItem: {
    flex: 1,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    borderRadius: 8,
    marginHorizontal: 3,
  },
  footerItemActive: {
    backgroundColor: '#243452',
    borderWidth: 1,
    borderColor: '#2f80ff',
    shadowColor: '#2563eb',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.22,
    shadowRadius: 12,
    elevation: 6,
  },
  footerIcon: {
    color: TEXT_MUTED,
    fontSize: 18,
    fontWeight: '900',
  },
  footerLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: '900',
  },
  footerActive: {
    color: '#38bdf8',
  },
});
